README.md
js/WebView.ios.js

Reference: #2 
This PR defaults this package to use WKWebView rather than UIWebView.
You can still use UIWebView (for now) by doing `useWebKit={false}`:
```
<WebView
useWebKit={false}
// ...
/>
```

Defaults to WKWebView instead of UIWebView

---

android/src/main/java/com/reactnativecommunity/webview/RCTWebViewManager.java

This is not usable currently because it does not compile for android. I need this because of this issue right now: https://github.com/facebook/react-native/issues/21104
Compiling for mac still does not work.

Fix compilation by renaming a class usage

---

README.md
docs/Custom-Android.md
docs/Custom-iOS.md
docs/Getting-Started.md
docs/Guide.md
docs/Reference.md

This migrates the WebView documentation into a local ./docs folder. I've also started a new Guide.md file that I'd like to flesh out with dozens of code examples to show the most common use cases and best practices.
In the future, I'd like to see pull requests include updates to appropriate `./docs` files as well. @Titozzz we should enforce this as we review PRs.
Fixes #36.

Migrate Documentation

---

ios/RNCWKWebView.m

WKWebView was not able to dealloc upon removal of components. It was due to registration of script message handler with strong reference to self, resulting the webview context to remain in memory until the app shuts down.
You can check it by
1. using WKWebView component (<WebView useWebKit={true}/>)
2. Open safari debug menu > your app.
You can see the JS contexts of WKWebView remaining even after react component has been destroyed.
Test Plan:
----------
1. Implement WKWebView in a react app
2. Browse a page
3. Remove the component from view hierarchy
4. Check safari debug menu to see if the webview has been dealloc-ed correctly.
Release Notes:
--------------
[IOS] [BUGFIX] [./ios/RNCWKWebView.m#99] - Deregister script message handler when webview is removed from view hierarchy

Fix WKWebView memory leak

---

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java

The fix code is taken from the last line of https://stackoverflow.com/a/10831462/728287
I'm testing Ukrainian Cyrilic characters
| Before        | After           |
| ------------- |:-------------:|
| <img src="https://user-images.githubusercontent.com/899175/46659207-25e7b600-cbbd-11e8-918f-0a1c6554e791.png" width="300" />   | <img src="https://user-images.githubusercontent.com/899175/46659209-2718e300-cbbd-11e8-84bc-f7c6e25b32ed.png" width="300" />
You can use this to test:
```jsx
<WebView
// source={{ uri: 'https://hostmaster.ua/' }} // no currently an issue with websites
source={{
html: `<html>
<head><meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0"></head>
<body>
<button id="btnSubmit">Створити картку</button>
</body></html>`,
}}
/>
```

Fix Android WebView when using UTF-8 characters (garbled output)

---

.releaserc
package.json
react-native-webview.podspec

Fix cocoapods install error and warning.
```
Fetching podspec for `react-native-webview` from `../node_modules/react-native-webview`
[!] The `react-native-webview` pod failed to validate due to 1 error:
- WARN  | attributes: Missing required attribute `license`.
- ERROR | version: The version of the spec should be higher than 0.
- WARN  | license: Missing license type.
- WARN  | source: Git sources should specify a tag.
```

Add license to podspec.

---

docs/Reference.md
ios/RNCWKWebView.h
ios/RNCWKWebView.m
ios/RNCWKWebViewManager.m
js/WebView.ios.js
js/WebViewTypes.js

Fixes [issue](https://github.com/facebook/react-native/issues/21336) for the WKWebView.
1. Add 'allowsBackForwardNavigationGestures' property to the iOS WKWebview

Add 'allowsBackForwardNavigationGestures' property to the iOS WKWebview

---

docs/Reference.md
ios/RNCWKWebView.h
ios/RNCWKWebView.m
ios/RNCWKWebViewManager.m
js/WebView.ios.js
js/WebViewTypes.js

Add 'userAgent' property to the iOS WKWebView. 
The property to set the userAgent in the iOS WKWebview is [customUserAgent](https://developer.apple.com/documentation/webkit/wkwebview/1414950-customuseragent). But to make the interface the same, I set userAgent props to WKWebview customUserAgent.

Add 'userAgent' property to the iOS WKWebView.

---

docs/Reference.md

Adds missing props into ref docs. I'd also found the following props in `js/WebView.android.js` which don't appear do anything.
* `onContentSizeChange` - android - obsolete as of API level 12
* `testID` no reference to this in the java code

Add docs for missing props which do something

---

ios/RNCWKWebView.m

There's currently a pretty major bug with WKWebView on iOS 12 that leaves the viewport awkwardly shifted upwards after the keyboard is dismissed. Makes using WebViews with forms an extremely janky experience.
https://openradar.appspot.com/radar?id=5018321736957952
The bug exists on any iOS 12 app compiled with Xcode 10 (which is almost all of them 😅)
This PR adds a keyboard listener that manually animates the content offset, shrinking it on keyboard dismiss. The solution is borrowed from this Ionic PR: https://github.com/ionic-team/cordova-plugin-ionic-webview/pull/201/files
The fix works seamlessly, however, I am unsure of what impact it may have elsewhere (if any).

Add fix for keyboard dismiss leaving viewport shifted in iOS 12

---

docs/Reference.md
ios/RNCWKWebView.h
ios/RNCWKWebView.m
ios/RNCWKWebViewManager.m
js/WebView.ios.js
js/WebViewTypes.js
typings/index.d.ts

Boolean value that determines whether pressing on a link displays a preview of the destination for that link. This is specific to iOS with devices that support 3D Touch.
**More info:**
https://developer.apple.com/documentation/webkit/wkwebview/1415000-allowslinkpreview

[ios] Add allowsLinkPreview property to WKWebView

---

docs/Reference.md

Add style doc, as discuss in #216, mention that if you need to add `flex: null` to make `height` work.

add style doc in reference.md

---

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java
android/src/main/java/com/reactnativecommunity/webview/RNCWebViewModule.java
docs/Guide.md

Addresses #80.
Caveat: I am not an Android developer. This code comes from a fork of the original RN WebView that we have been using in production for some time, so all credit goes to @Oblongmana: https://github.com/Oblongmana/react-native-webview-file-upload-android.
Setting up a DownloadManager for the WebView is pretty straightforward, as is adding any known cookies to the request. Most of the complication comes from the requirement after SDK 23 to ask the user for the WRITE_EXTERNAL_STORAGE permission. Unfortunately there is no mechanism to suspend the download request until permission is resolved so this code stores off the request and sets up a listener that enqueues the download once permissions are resolved so the user experience is really nice.
I didn't see anything in the way of …

Add file download support for Android

---

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java

The current implementation of `onContentSizeChange` uses an old deprecated API [setPictureListener](https://developer.android.com/reference/android/webkit/WebView.html#setPictureListener(android.webkit.WebView.PictureListener)) - it was deprecated in API 12 but this library is set to a minimum of API 16 - this API most likely doesn't exist on devices using newer APIs 💥 
I've swapped it out for [WebView#onSizeChanged](https://developer.android.com/reference/android/webkit/WebView#onSizeChanged(int,%20int,%20int,%20int))
- [ANDROID] [FIX] `onContentSizeChange` now uses `WebView`s own `onSizeChanged` events instead of the now deprecated API `setPictureListener`.

[android] replace deprecated `WebView.PictureListener`->`onContentSizeChange` impl

---

docs/Reference.md
ios/RNCWKWebView.h
ios/RNCWKWebView.m
ios/RNCWKWebViewManager.m
js/WebView.ios.js
js/WebViewTypes.js

Allows the webview to be opened with an ephemeral data storage.
Looks like there is no out-of-the-box support for `UIWebView` so I didn't implement that.
I think there should be a relatively simple way to implement this on Android as well.

Add incognito prop to iOS WKWebview

---

ios/RNCWKWebView.m

Adds the same code that is on `RNCUIWebview` https://github.com/react-native-community/react-native-webview/blob/master/ios/RNCUIWebView.m#L271 for the same purpose.
I came across this problem while implementing google SAML support with the RNCWKWebView.

Add "Frame load interrupted" error handling for OAuth for RNCWKWebView

---

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java
docs/Reference.md
js/WebView.android.js
js/WebViewTypes.js
typings/index.d.ts

Hardware acceleration is enabled by default if your Target API level is >=14. However, because hardware acceleration is not supported for all of the 2D drawing operations, turning it on might affect some of your custom views or drawing calls. To disable hardware acceleration in application level will slow down the app, so we'd better to add a prop to enable user to disable hardware acceleration for android platform in view level
Please view the details in [Hardware acceleration](https://developer.android.com/guide/topics/graphics/hardware-accel#controlling)

Add `androidHardwareAccelerationDisabled` prop

---

babel.config.js
docs/Contributing.md
jest.config.js
js/WebViewShared.js
js/__tests__/WebViewShared-test.js
js/__tests__/__snapshots__/WebViewShared-test.js.snap
package.json
yarn.lock

Currently URI schemes that contain +,-, or . are not supported. We are working on adding a custom scheme for WKWebView that contains a + character. It would never allow our scheme to pass the whitelist.
An additional bug was preventing unwanted characters before a valid scheme. For example fakehttp://example.com would pass the whitelist because the regex was not matching from the start of the string.
Also added support for Jest tests and added tests for the changes.

Support all valid URI schemes and add testing

---

package.json

Fixes #279
The react-native version of peerDependencies remained at "^0.57".

Fix peerDependencies >=0.57 <0.59 (#279)

---

docs/Reference.md

according to https://github.com/react-native-community/react-native-webview/commit/b1b662628e3ceb5c89f1d105814f01c4aba0b701 it's supported on android and Ios so  no platform  reference is needed

Deleted onShouldStartLoadWithRequest platform reference

---

typings/index.d.ts

This `cacheEnabled` prop was added in PR #152 but the typescript compiler was giving me an error when I tried to use it, so I've added it to the typescript declaration file.
I think this is a fairly simple and self-explanatory PR but let me know if you need any other details! 😃

Add `cacheEnabled` prop to typescript prop type declarations

---

ios/RNCWKWebView.m

This PR fixes two crashes when enableWebKit is true (which was the default) on iOS 9.x. The first one when the WebView component was mounted (fixes issue #150) and the second one, when the component was unmounted (fixes issue #213).
The first problem happen when the RNCWKWebView.m was loaded:
The programming guide for WebKit (version 2006) ([pdf](http://mirror.informatimago.com/next/developer.apple.com/documentation/Cocoa/Conceptual/DisplayWebContent/WebKit_DisplayWebContent.pdf)) from Apple said, that it is (was) required to check if the 'new' WebKit Framework was available. This was required when the WebKit framework was only available on Mac OS X (10.2) when the Safari was installed. 😆
Because WebKit is (currently..) a fix part of iOS we didn't need this check this anymore to …

Fix crash with WebKit on iOS 9.x.

---

docs/Reference.md
ios/RNCWKWebView.m

I have a [demo](https://github.com/ccorcos/react-native-demo/tree/resize-bug-2) and a [demo fix](https://github.com/ccorcos/react-native-demo/tree/resize-bug-2-fix) showing how focusing an input towards the bottom of the screen causes the scroll view to shift the entire page. If `scrollEnabled={false}` then its impossible to scroll the body back into view. The image below shows what's going on.
This PR overrides the scroll view delegate to prevent this shift from occurring.

Don't allow the scrollView to scroll when `scrollEnabled={false}`.

---

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewModule.java

The current implementation doesn't support a list of file extensions in the accept attribute (e.g. `<input type="file" accept=".jpg, .png">`) while that is a valid value per the HTML spec. I've updated the implementation to convert any file extensions to mime types before we set the type(s) on the intent to rectify the issue. In addition I've updated the `acceptsImages` and `acceptsVideo` methods to handle file extensions as well.

Android: Support file extensions in file input accept attributes

---

docs/Reference.md

Add example uses of
- onError
- onLoad
- onLoadEnd
- onLoadStart
- onLoadProgress
- onNavigationStateChange
- originWhitelist
- renderError
- renderLoading
- style

Add API Examples in reference documentation

---

README.md

The link was missing in the README for the getting started page, the square brackets were there though so looks like whoever wrote it just forgot to put the link there.

Add getting started doc link

---

docs/Guide.md
docs/Reference.md

I've added a new guide section for communication between React Native and the web pages themselves to `Guide.md`, including `injectJavaScript`, `injectedJavaScript`, `onMessage`, and `postMessage`. I've also added some missing in-document links and linked the `Reference.md` to the new guides.

Added guides for communication between React Native and web pages

---

typings/index.d.ts

This static async function was missing a type definition for typescript so I added one 😄 
Before:
After:

Add typescript definition for isFileUploadSupported

---

index.d.ts
package.json

- fix syntax of type declarations
- point `typings` field in package.json to actual declaration file
See discussion in https://github.com/react-native-community/react-native-webview/pull/442#issuecomment-476251815

Fix typings

---

src/WebViewTypes.ts

See issue #452 for more details.
Closes #452.

Make WebViewSourceHtml.baseUrl optional

---

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewModule.java

The app was crashing with `"Could not find @ReactModule annotation in class RNCWebViewModule"` exception. Searching for this message in RN's code I found [this commit](https://github.com/facebook/react-native/commit/0cd3994f1a4ec1172af840cf5de3dddb1ae9e9c4), introduced in React Native 0.58, which requires native modules to be annotated with @ReactModule annotation. 🤔 
After adding the annotation to the module, tapping on a file input field no longer crashes the app (in fact it shows the file browser). 🎉 
I haven't had caught it previously, testing only against React Native 0.57, sorry! 😞 
For reference see similar fix in `react-native-gesture-handler` — https://github.com/kmagiera/react-native-gesture-handler/pull/295.
Fixes https://github.com/react-native-community/react-native-webview/is …

fix(android): Annotate RNCWebViewModule with @ReactModule to comply with latest changes

---

src/WebView.styles.ts

Fixes #475
#472 added a `backgroundColor` of `white` to the `container` style which broke the ability to set a `transparent` background color on the `WebView` component. This simply removes that unnecessary style.

Removes hard-coded container white backgroundColor

---

docs/Reference.md

There is a duplicate example for onShouldStartLoadWithRequest. This removes the duplicate example.

Remove duplicate example of onShouldStartLoadWithRequest

---

README.md

Per @Rinkuk1993's [comment](https://github.com/react-native-community/react-native-webview/issues/437#issuecomment-480158586), the changelog might confuse some people as to what version is latest, so I've added a "latest version" badge to the README in two places. I've also reversed the order of the changelog so the most recent is at the top.

Adds version badge to README

---

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java

While doing some testing of using the `source.html` prop and setting it to raw HTML, I noticed that changing the raw HTML didn't cause an update of the displayed WebView content on Android. iOS works fine.
Doing some research finds a lot of people online encountering bugs with the `WebView.loadData` function. For example:
- https://stackoverflow.com/questions/4096783/android-webview-1st-loaddata-works-fine-subsequent-calls-do-not-update-disp
- https://stackoverflow.com/questions/17501860/had-to-load-data-twice-to-make-webview-refresh-in-android
The recommendation that this PR follows is to never use `loadData` and instead always use `loadDataWithBaseURL` and just don't pass in a `baseUrl` if we don't have one.

fix(android): updating source.html prop doesn't refresh webview

---

ios/RNCWKWebView.m

This crash is found in our fabric.
I can't reproduce it.
But this protection is needed because in Apple's doc the title property is nullable.

fix: iOS crash when WebView's title is nil

---

src/WebViewTypes.ts

`onLoadingProgress(event: WebViewProgressEvent)` uses wrong parameter type. 
It uses `WebViewProgressEvent` but should use  `NativeSyntheticEvent<WebViewProgressEvent>,` similar to `WebViewEvent`.
If you use the typescript definition as implement like:
```
private onLoadProgress(event: WebViewProgressEvent) {
this.setState({ loadingProgress: event.progress });
}
```
`event.progress` is always `undefined`. You can use the progress with `event.nativeEvent.progress` but then you will get a typescript error.

wrap WebViewProgressEvent into NativeSyntheticEvent

---

docs/Reference.md
ios/RNCWKWebView.h
ios/RNCWKWebView.m
ios/RNCWKWebViewManager.m
src/WebViewTypes.ts

This is an attempt at solving https://github.com/react-native-community/react-native-webview/issues/278 for iOS. It introduces a new prop called `keyboardDisplayRequiresUserAction`. Setting it to `false` will allow the WebView to bring up the keyboard on focus events. It works on 9.0-12.2. It works by swizzling WKContentView, with different versions for the 11.3-12.20+ ranges.
Created a new app using react-native init using my modified version, setting `https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_text_autofocus` as the source. When set to false, it would autofocus, when set to true it didn't. I also tried combining it with `hideKeyboardAccessoryView` which also swizzles, and all combinations worked fine.
Please let me know what else needs to be done, such as updating docs? …

feat(WKWebView): Allow focus without user interaction

---

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java

After changed the props "androidHardwareAccelerationDisabled" to false, changing it to back to true will not re-enable hardware acceleration in Android

 Fix unable to re-enable hardware acceleration after disabled it

---

docs/Guide.md
docs/Reference.md

Per @janicduplessis's [comment](https://github.com/react-native-community/react-native-webview/issues/24#issuecomment-483956651) on issue #24, there's a decent workaround to capturing hash URL changes. I've added this to the Guide.md file.
There are a bunch of Prettier updates as well. We should probably run Prettier on the whole project and add `lint-staged` and `husky` to avoid this issue in the future. I'll work on that if @Titozzz agrees.

Adds guide for intercepting hash URL changes

---

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java
docs/Reference.md
src/WebView.android.tsx

Fixes https://github.com/react-native-community/react-native-webview/issues/294.
Let me know if we want to add anything as part of this.

Support fullscreen video on Android

---

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java

`getJSEventName()` needs a ScrollEventType parameter.
```java
public static String getJSEventName(ScrollEventType type) {
switch (type) {
case BEGIN_DRAG:
return "topScrollBeginDrag";
case END_DRAG:
return "topScrollEndDrag";
case SCROLL:
return "topScroll";
case MOMENTUM_BEGIN:
return "topMomentumScrollBegin";
case MOMENTUM_END:
return "topMomentumScrollEnd";
default:
throw new IllegalArgumentException("Unsupported ScrollEventType: " + type);
}
}
```

fix Java syntax error

---

README.md
android/gradle.properties
android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java
docs/Getting-Started.md

Hello, in order to use react-native-webview > 6.0.0 please make your android/build.gradle contains:
```
android.useAndroidX=true
android.enableJetifier=true
```
This enables AndroidX libraries which are the new standard.

fix(AndroidX support): Fixed broken import + added instructions

---

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java

Scrolling event processing continues to occur internally on Android, even if the `onScroll` property is not set. I don't think it's efficient.
Not required.
| iOS     |    -     |

fix(performance): Improved `onScroll` to work efficiently on Android

---

src/WebView.android.tsx
src/WebView.ios.tsx
src/WebView.styles.ts
src/WebViewShared.tsx

I am using react-native-weview on an app, and it works very well. But, when I introduced a custom loading screen, I noticed a very odd bug in the application of CSS to the webpage inside the webview. This is best explained via screenshots: 
Before using `startInLoadingState={true}`
After using `startInLoadingState={true}`
Notice that the bar at the bottom of the webview has a blur effect in the first screenshot, but no blur effect in the second screenshot. The css applied to the underlying site has not changed. To reproduce, load a webpage in the webview with an element that has `-webkit-backdrop-filter: blur(20px);` and something colorful behind it (so you can see the blur effect). The URL of the page in the screenshot is `https://review.discourse.org`. 
The source of the issue is that …

Fix CSS rendering bug when using startInLoadingState

---

.github/CODEOWNERS

Per https://github.com/react-native-community/.github/issues/1#issuecomment-496203158
This adds @Titozzz and @jamonholmgren as code owners. We can add others to various parts of the file as we recruit more maintainers for this repo.

chore(docs): Add CODEOWNERS file

---

src/WebViewTypes.ts

Followup to https://github.com/react-native-community/react-native-webview/pull/506

fix(types): Add missing applicationNameForUserAgent type

---

src/WebViewTypes.ts

Adds missing `allowsFullscreenVideo` prop to the types in `WebViewTypes.ts` after https://github.com/react-native-community/react-native-webview/pull/325 got merged.
1. Compile the app with new property.
2. Verify it compiles properly. 😆 
- [ X] I updated the typed files (TS and Flow)

Add missing allowsFullscreenVideo to WebViewTypes.ts

---

README.md

Expo SDK 33 is now use React Native WebView https://blog.expo.io/expo-sdk-v33-0-0-is-now-available-52d1c99dfe4c
update the support state in README

Update Expo support state in README

---

package.json

As described in the [NPM documentation](https://docs.npmjs.com/misc/scripts#prepublish-and-prepare), the `prepare` script should be used for essential build tasks.
In practice, this makes it possible to depend on `react-native-webview` via git. If I contribute a new feature, I can use the feature right away by depending on its git branch, without waiting for upstream to publish, or even approve my pull request. This is great for experimentation.
Verify that existing features still work:
Verify that new features work:
This project does not have a `CHANGELOG.md` file! Also, none of the other steps are applicable to this change.

Switch from `prepack` to `prepare`

---

react-native-webview.podspec

Add version tag to `react-native-webview.podspec`.

Add version to podspec

---

docs/Getting-Started.md

I believe the getting started guide leaves out that you need to run `pod install` after running the link command. Otherwise the cocoapod will never actually be linked.
This was at least the case with my project, although interested to hear if I am wrong.

Add pod install step to getting started guide

---

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java
docs/Reference.md
src/WebViewTypes.ts

Allows the webview to be opened with an ephemeral data storage.
Follow-up to https://github.com/react-native-community/react-native-webview/pull/148.
Closes https://github.com/react-native-community/react-native-webview/issues/737

Add incognito prop to Android RNCWebViewManager

---

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java
docs/Reference.md
src/WebViewTypes.ts

This will make the `applicationNameForUserAgent` cross platform.
This prop was originally added in https://github.com/react-native-community/react-native-webview/pull/506
Note: There was a TODO in the area I was working about handling unsetting of the `userAgent` prop so I did that too.
| iOS      | Android |
| ------- | ------- |
| ![Screen Shot 2019-07-08 at 5 52 37 PM](https://user-images.githubusercontent.com/333260/60845094-3c9d5680-a1a9-11e9-94ba-e05f35ca8044.png) | ![Screen Shot 2019-07-08 at 5 54 59 PM](https://user-images.githubusercontent.com/333260/60845183-89812d00-a1a9-11e9-9147-9fe2d1a22a58.png) |
```
<WebView
source={{ uri: `https://www.whatsmyua.info/` }}
applicationNameForUserAgent={"DemoApp/1.1.0"}
/>
```
See that on both iOS and Android the Application name is now …

polyfill applicationNameForUserAgent on Android

---

ios/RNCWKWebView.m

When calling `window.prompt(text, defaultText)` on iOS, `react-native-webview` doesn't render the cancel button. Also `defaultText` is incorrectly set to the placeholder text which disappears once the user starts typing.  
This issue does not affect Android. 
**Desired behaviour as comparing to Mobile Safari**
**Existing behaviour**
**After the fix**
Render
`<WebView source={{ uri: 'https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_prompt' }} />`
And click on the "Try it" button.
This issue does not affect Android.

Align look and feel of Window.prompt() to Mobile Safari

---

ios/RNCWKWebView.m

* What issues does the pull request solve? Please tag them so that they will get automatically closed once the PR is merged #502 
* Changes error/redbox into warning/yellowbox on evaluating bad injected JS. So wouldn't crash production releases
* Warning added actual error, useful for debugging bad JS injected into webview
* callback runs, whether there's error or not. As used in my app (https://medium.com/wonderswipe/rethink-mobile-search-10-100x-faster-introducing-wonderswipe-6f2ff0d0e667) which injects JS into sanitized html from the wild, small error in injected JS doesn't warrant the whole JS payload from being injected/run
On Android, error evaluating injectedJavaScript currently fail …

Fixes #502. Error evaluating injectedJavaScript should be warning instead of redbox error

---

ios/RNCWKWebView.m

iOS 13 has included [webkit change](https://github.com/WebKit/webkit/commit/3d92cb040253760233028c6c13c9e940744f5265) that has renamed the signature of `_elementDidFocus` method
Retesting https://github.com/react-native-community/react-native-webview/pull/540 usign iOS 13

Fix signature of the swizzled `elementDidFocus` method on iOS 13

---

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java

fix #760 according to the call stack. It seems caused by the mRNCWebViewClient was set to null after runnable being executed asynchronously.

add null reference check for onMessage on android

---

docs/Reference.md
ios/RNCWKWebView.m
ios/RNCWKWebViewManager.m
src/WebView.ios.tsx
src/WebViewTypes.ts

This controls the way iOS will automatically adjust the insets when the
webview is behind things like the iPhone X notch.
On devices like the iPhone X, the WebView will put part of the content under the notch, by default.
Add a new prop `contentInsetAdjustmentBehavior` (just for iOS) that lets users tell the webview to adjust content automatically.
This is a copy (more or less) of the implementation that exists in react-native-wkwebview-reborn.
Running on iOS w/o the change:
Running on iOS w/ the change (and passing "always" to `contentInsetAdjustmentBehavior`):
Also I ran the code on Android JIC (setting the prop) and everything was fine.
No prereqs.
Running an app w/ the WebView (taking up a large amount of screen space) on an iPhone X, rotate the device, notice the webview content …

Adding a `contentInsetAdjustmentBehavior` prop to the WebView for iOS.

---

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java

This change updates the fullscreen video support in Android to match the behavior in iOS so that the user can rotate the screen regardless of the default orientation defined in the app. For example, if `android:screenOrientation="portrait"` is defined within the manifest, then the video will always displayed in portrait mode regardless of the aspect ratio in the video. Related to https://github.com/react-native-community/react-native-webview/issues/586. Also see Android X version of this PR at https://github.com/react-native-community/react-native-webview/pull/816  
This change also avoids some of the pitfalls of forcing screen orientation discussed in https://github.com/react-native-community/react-native-webview/pull/325#pullrequestreview-203973316 
- Set …

Allow user to rotate fullscreen video on Android (No Android X)

---

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java

This change updates the fullscreen video support in Android to match the behavior in iOS so that the user can rotate the screen regardless of the default orientation defined in the app. For example, if `android:screenOrientation="portrait"` is defined within the manifest, then the video will always displayed in portrait mode regardless of the aspect ratio in the video. Related to https://github.com/react-native-community/react-native-webview/issues/586. Also see non-Android X version of this PR at https://github.com/react-native-community/react-native-webview/pull/815  
This change also avoids some of the pitfalls of forcing screen orientation discussed in https://github.com/react-native-community/react-native-webview/pull/325#pullrequestreview-203973316 
- Set …

fix(android): Allow user to rotate fullscreen video (Android X)

---

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java

Crashes when open webview with `incognito` in Android SDK 16. https://github.com/react-native-community/react-native-webview/issues/794. Added SDK checking for `removeAllCookies` where it's not available before SDK 21
Tested with Android Lollipop and Pie emulator, no crash when view webview with `incognito` props.
Android Lollipop device
Install app in Android Lollipop devices and open the webview with `incognito` (true or false)

Fix webview crash with incognito in Android Lollipop

---

docs/Reference.md
ios/RNCWKWebView.h
ios/RNCWKWebView.m
ios/RNCWKWebViewManager.m
src/WebViewTypes.ts

By default, the WKWebView sets `allowingReadAccessToURL` to just the file itself when provided with `source={{ uri: 'file://myFile' }}`. This means that it's not possible to access any other CSS or JS on the filesystem from within the WebView.
This change adds a prop that lets users customize `allowingReadAccessToURL`. The default is still to only allow access to just the file itself, but users can now override it.
**Important: allowingReadAccessToURL is ignored on the emulator. This must be tested on your device**
See https://github.com/hsource/test-allowing-read-access/tree/master
To test that it works:
1. Clone the test repository `git clone https://github.com/hsource/test-allowing-read-access.git`
2. Go into the directory and run `yarn install` and `cd ios; pod install; cd ..`
3. Go …

Add prop for allowingReadAccessToURL on iOS WKWebView

---

ios/RNCWKWebView.h
ios/RNCWKWebView.m
src/WebView.ios.tsx
src/WebViewTypes.ts

When opening Google Docs in the IOS WebView
If `JavaScriptEnabled` is true, Google Docs will have a header.
There is also a page called Clear the cache and the cookies.
I fixed this problem by adding `javaScriptEnabled` to IOS.
One `javaScriptEnabled` variable and five lines of code have been added.
I used javaScriptEnabled in `WKPreferences`.
In addition to the issues I mentioned, you can solve problems that occur when iOS can not use `javaScriptEnabled` as false.
Just add 5 lines to RNCWKWebView.m.
```
WKPreferences * prefs = [[WKPreferences alloc] init];
     if (! _ javascriptEnabled) {
       prefs.javaScriptEnabled = NO;
       wkWebViewConfig.preferences = prefs;
     }
```
The simplest test is to open Google Docs with WebView in IOS.
| ------- | …

add-javaScriptEnabled-in-IOS

---

ios/RNCWKWebViewManager.m

After the 6.11.0 release injectedJavascript stopped working. This fixes that.
Tested on real device and emulator with javascriptEnabled prop set to true and false

Fixed javaScriptEnabled property

---

android/build.gradle

Each time building our app, this library causes a message like this
one to be printed, sometimes twice:
> Configure project :react-native-webview
:react-native-webview:reactNativeAndroidRoot /home/greg/z/mobile/node_modules/react-native/android
Worse, the message comes through even if I silence all normal
progress messages and warnings, with `./gradlew --quiet`.
It turns out that the `logger.quiet` method which these log lines are
using has a confusing name.  It doesn't mean "log quietly", but more
like the opposite: "log even when asked to keep things quiet".  See
documentation on Gradle log levels:
https://docs.gradle.org/current/userguide/logging.html
So, remove the noise by switching to `logger.info`.  This avoids
bothering the user by default, and keeps the information readily …

fix(android): Move noisy debug logging out of "quiet" log level.

---

package.json

This adds the metadata used by react-native-website to include the Webview component back in the API documentation.

chore(docs): add documentation meta data

---

ios/RNCWebView.m

It's not safe to convert NSString to NSURL by URLWithString directly.
If NSString is not a valid URL (maybe contains some special characters), it will return nil.
This PR change URLWithString into RCTConvert.
Not only fix the above issue but prop allowingReadAccessToURL also don't need the file:// prefix.
[Test repository](https://github.com/hank121314/iOS_WKWebview_Test)(reference to: https://github.com/hsource/test-allowing-read-access/tree/master)
1.Clone the test repository and
`yarn && cd ios && pod install`
2.Run on a real device.

Fix(iOS):use RCTConvert to convert allowingReadAccessToURL.

---

index.d.ts

This change simply exports `WebViewMessageEvent` and `WebViewNavigation` so consumers can type check their callbacks.
Everything should build successfully as usual.

fix(types): Export WebViewMessageEvent, WebViewNavigation for external use

---

docs/Reference.md

After needing to see what the origin of a "html" source'd WebView would be, I found the documentation that baseUrl would be utilized for the "origin" header when CORS requests are made.

chore(docs): Update "source" doc, baseUrl comments about CORS

---

src/WebView.android.tsx
src/WebView.ios.tsx

In https://github.com/react-native-community/react-native-webview/pull/847 we changed how we were calling `dispatchViewManagerCommand`, instead of passing `null` as the final argument (`commandArgs`) we switched to just leaving the argument off. The react-native types specify this as an optional param, but really that type should be `any[] | undefined`. As such this seemed like a safe change to make, when in fact it was not because react native is strict about argument counts, meaning that **anyone who upgrades to 7.07 gets a crash when using any of `goBack`/`goForward` etc methods**. Because this is a patch release it's very possible that people will accidentally upgrade to this version. 
This PR switches to using `undefined` which both matches the RN types and satisfies the argument …

Call dispatchViewManagerCommand with correct number of arguments

---

src/WebViewTypes.ts

Based on the documentation, `onContentProcessDidTerminate` should be optional but it isn't in typing.
It should build successfully.
| Android |   ❌     |

fix(types): Make onContentProcessDidTerminate optional

---

ios/RNCWebView.m

UIWindowDidBecomeVisibleNotification and UIWindowDidBecomeHiddenNotification seem to be far more reliable events to detect when the video enters or leaves fullscreen
This should fix the following bug: https://github.com/react-native-community/react-native-webview/issues/735
I tested the code on iOS 12 and 13. No other tests have been done so far. But it seems to work properly.
| Android |    not affected    |
- [  ✅  ] I have tested this on a device and a simulator
- [ not needed ] I added the documentation in `README.md`
- [ might not be needed ] I mentioned this change in `CHANGELOG.md`
- [ not needed ] I updated the typed files (TS and Flow)
- [ not needed ] I added a sample use of the API in the example project …

fix(iOS): Fix changing notification bars #735

---

src/WebView.android.tsx

It might still trigger loading progress event (to 100/100) after error being received in Android WebView. As a result, the previous `ERROR` state will be overwritten to `IDLE` in `onLoadingProgress()` and the view created by `renderError()` won't be visible in this case.
- use the WebView with `renderError` props set
- set a incorrect url to load - e.g. http://www.google.com1
- check if the `renderError` contents are visible

fix(android): renderError - the error status might be overwritten by loading progress event

---

docs/Reference.md
src/WebView.android.tsx
src/WebView.ios.tsx
src/WebViewTypes.ts

Me and my team need to use the `WebView` to display error from server (in HTML format) inside modals.
The `flex: 1` in the container style doesn't allow us to style the modal as the UX/UI team wants to.
With this `prop` we can set `flex: 0` and style the container and the `WebView` as we want.
`yarn ci` runs without any issue.

feat(new prop): containerStyle

---

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java

Fixes #802 and solves the issue #894 was opened for.
`RNCWebViewManager`'s `onPermissionRequest` attempts to act on a `PermissionRequest` object but `PermissionRequest` wasn't introduced until API 21 (https://developer.android.com/reference/android/webkit/PermissionRequest). There's currently a linter error getting thrown because there's nothing that accounts for this API level requirement.
This PR adds `@TargetApi(Build.VERSION_CODES.LOLLIPOP)` to the method so the linter passes successfully and allows the project to continue to support API level 16.
`lint` should pass.
| iOS     |    N/A     |

Add TargetAPI of Lollipop to Android's onPermissionRequest

---

src/WebView.android.tsx

this commits is try to resolve the crash problem while use 'require(./XXX.html)' to load local html, 
such as:
```
render(){
const uri = require('../../Resources/index.html')
<WebView
style={styles.webview}
originWhitelist={['*']}
source={uri}   
/>
}
```
What's required for testing (prerequisites)?
Running on Android
| Android |    ✅   |

fix(android): crash problem while loading local html resource

---

docs/Guide.md

Fixes #746 
These steps are based on my other project React native draftjs which requires loading a local HTML file. The code can be found in the following line - https://github.com/DaniAkash/react-native-draftjs/blob/bc51410117d238e0f67f90e614fe11aacf41843b/index.js#L113
There is a project implement using this method - [React Native Draftjs](https://github.com/DaniAkash/react-native-draftjs) which can be referred for proper functioning of this feature.
A simple html and loading in the webview will do.
| iOS     |    ✅    |

chore(docs): Steps to load local HTML files into the webview

---

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java

A ClassCastException occurs when setWebViewClient() is called on Android native.
I access the RN webview on Android native by casting to an Android webview to add custom functionality. Calling setWebViewClient() thereafter caused a ClassCastException.
Running on Android
1. Access the RN webview object on Android
2. Cast to Android WebView
3. Call setWebViewClient()

Fix ClassCastException

---

.github/workflows/detox.yml

install exact version instead of latest one
I added exact version for `gem install` in order to make CI more stable.
v 1.8.4 is the latest one and being used currently in this project.

chore(buildtools): Use fixed version of cocoapods gem on ci

---

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java

Fixes crash when HTML5 video doesn't have post image, link to issue:
https://github.com/react-native-community/react-native-webview/issues/1026
- [x ] I have tested this on a device and a simulator

fix(android): Added fallback poster image to prevent crashes

---

docs/Guide.md
ios/RNCWebView.m

Resolving merge conflicts for https://github.com/react-native-community/react-native-webview/pull/652
> This pull request solves #24, where navigating the WebView using the window.history API doesn't generate any events on iOS. This seems to be a low-level problem with the WKWebView, since none of the WKNavigationDelegate methods fire in these cases.
> 
> Since the native code doesn't tell us when the location changes this way, the semi-hacky solution is to inject Javascript into the user page. This Javascript intercepts calls to the window.history API and sends an event to the native code when this happens. The native code then fires an onLoadingFinish event, just like Android.
> 
> When I first implemented this, I didn't realize that the guide actually included a similar solution as the …

feat(ios): Generate history API events on iOS

---

ios/RNCWebView.h
ios/RNCWebView.m

When close the webview, dealloc function does not execute, there have a retain cycle in RNCWebView.m file
NO
Hit berakpoint in dealloc function，after the webview close，this function is not excute

fix:iOS WKWebView RetainCycle

---

src/WebViewShared.tsx
src/__tests__/WebViewShared-test.js

This PR does two pretty small and related things (in two commits):
When the WebView tries to load a URL from an un-whitelisted origin, react-native-webview calls `Linking.openURL` and lets the OS handle it.  But, sometimes there is an error on the native side of `Linking.openURL`, for example on Android if the URL is like `intent://....` but there is no Activity that can handle that intent installed.  This results in an unhandled promise rejection because no code is `catch`ing the error. 
We track and handle unhandled promise rejections in our app, and send them to our crash/analytics service as errors.  This is not _really_ an error though, so its just noise.  Actually another concern is that it possibly has user info (in the URL) that we don't want to be storing either.  
Anyways, the …

Two tweaks to how URLs from un-whitelisted origins are handled

---

ios/RNCWebView.m

I intend to implement updatable user scripts (i.e. user scripts such as injected JS would be updated upon props change), and this will involve removing and re-adding all scripts on the `wkWebViewConfiguration`.
A necessary first step is to extract all the config setup from `didMoveToWindow()` into a separate function. This is beneficial anyway as `didMoveToWindow()` is enormous and hard to analyse at the moment due to all this logic.
This purely a function extraction and will not impact the library.
None; minor change.
None; minor change.
None; minor change.
| Android |    N/A     |

Extract wkWebViewConfig setup into setUpWkWebViewConfig function

---

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java

Reverts react-native-community/react-native-webview#991.
This is causing a bug where we can never prevent a page from loading by returning false in `onShouldStartLoadWithRequest`.

Revert "fix(android): redirected URL cannot be loaded normally."

---

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewModule.java
docs/Guide.md
example/App.tsx
example/android/app/src/main/AndroidManifest.xml
example/examples/Uploads.tsx

Don't show camera options for a file upload that would result in nothing happening for the user.
On Android, if the application declares the camera permission, then even intents that use the camera require permission to be granted. This is a problem for apps that combine an in-app camera with a WebView that has file uploading and the user has not given permission for the camera.
Note, this will not request permission for camera. This will simply prevent showing the camera options that would be a no-op action for users. It does this by checking if the camera permission is declared, and if so, checks that the user has granted permission.
[More information on this camera permission/intent issue.](https://blog.egorand.me/taking-photos-not-so-simply-how-i-got-bitten-by-action_image_capture/) …

fix(Android): Don't show camera options for a file upload when they can not be used

---

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java

It's bad to log the cookie, as it contains sensitive information.
This PR stops the android webview from logging the cookie when downloading a file.
https://source.android.com/security/best-practices/privacy
https://readwrite.com/2012/04/10/what-developers-and-users-can/
https://source.android.com/security/best-practices/privacy

fix(Android): Don't log the cookie when downloading file.

---

src/WebViewTypes.ts

When you try to compile this lib in a project with a version of typescript < 3, it will fail.
It fails because the WebViewTypes.ts has the readonly definition, written in the wrong place.
this will resolve the following bug:
Bug when compile WebViewTypes.d.ts with Typescript #1267
Compile with typescript version > 2
Typescript version 2 >
The compilation of your project will not fail.

Fix: Moved readonly definition in WebViewTypes.ts

---

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java
package.json
src/WebView.android.tsx
src/WebViewTypes.ts
yarn.lock

Fixes
- https://github.com/react-native-community/react-native-webview/issues/1295
- https://github.com/react-native-community/react-native-webview/issues/1300
which were introduced in 9.1.0 after merging https://github.com/react-native-community/react-native-webview/pull/1203
This is done by binding a separate module to each WebView that is used.
Unfortunately I came up with no better way to do the uniqueness except by a random string. If anyone has any ideas, I'm all ears.
Other things I tried:
- ref, which is not easily converted to a unique string
- nativeTag, which is a private parameter on Component
- UUID, for generation of which we'd need to include a library
- Include two separate WebView components with a unique onMessage handler for each
- Send a message to React Native layer …

Ensure each mounted WebView binds their personal onMessage handler

---

apple/RNCWebView.m
apple/RNCWebViewManager.m
docs/Guide.md
docs/Reference.md
example/App.tsx
example/examples/Downloads.tsx
example/ios/Podfile.lock
index.d.ts
src/WebView.ios.tsx
src/WebViewTypes.ts
yarn.lock

This PR adds an optional iOS-only callback `onFileDownload` to react-native-webview to help support file downloads.
Our application uses `react-native-webview` and has many parts of web-app that serve file downloads.
`onFileDownload` is called with the URL that you can use to download the file. When RNCWebView detects that the HTTP response should result in a file download, `onFileDownload` is called. The client can then provide code to download the file.
RNCWebView determines that a file download should take place if either of the following is true:
1. The HTTP response contains a `Content-Disposition` header that is of type 'attachment'
2. The MIME type of the response cannot be rendered by the iOS WebView
The primary component of this PR is the change to …

feat(iOS): iOS file downloads

---

windows/ReactNativeWebView/ReactWebView.cpp
windows/ReactNativeWebView/ReactWebViewManager.cpp

Fix ScriptNotify to allow for JSON objects - the alert handler shouldn't consume any and all json objects. I also prefixed the type with double underscore to avoid collision with valid use cases where someone might want to use "type":"alert"
Fix InjectJavaScript, which wasn't parsing the command args correctly and so was always injecting an empty string.

Fix windows ScriptNotify and InjectJavaScript

---

apple/RNCWebView.m

This allows apps to correctly react when the app is loaded but the webview has been removed from memory. This is very tricky to test, but it happens when returning from background after medium periods of inactivity (not too long so the full app is out of memory, but long enough for the OS to remove the webview from memory). 

fix(iOS): Trigger _onContentProcessDidTerminate when removing webview from superview

---

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewModule.java

fixes #1121
when requesting a file upload with an unknown extension on android, getAcceptedMimeType returns [null] resulting in an exception when trying to test if array is empty.
fixes #1121
see https://github.com/react-native-community/react-native-webview/issues/1121#issuecomment-625230364

add missing null check for fileTypes

---

android/gradle.properties
android/src/main/java/com/reactnativecommunity/webview/RNCWebViewModule.java
docs/Guide.md
example/android/build.gradle

Fix the issue where permission request is prompted for saving files when it's not needed on Android Q and above. Also fixes an issue with not checking WRITE_EXTERNAL_STORAGE manifest permission for Android versions below M.
See: https://developer.android.com/reference/android/Manifest.permission#WRITE_EXTERNAL_STORAGE
Expected/new behavior for grantFileDownloaderPermissions():
1. Android version below M, if permission not included in the manifest: return false
2. Android version below M, if permission included in the manifest: return true
3. Android version M-Q, if permission already granted for app: return true
4. Android version M-Q, if permission not granted for app: request runtime permission and return false
5. Android version Q and above: permission not required; return true

Fix the issue where permission request is prompted for saving files when it's not needed on Android Q and above

---

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java

#1373 and #1298 both introduced an overwrite of `setWebChromeClient()`.
This PR combines the changes into one overwrite.
Closes #1415, #1416

fix(android): duplicate `setWebChromeClient()` overwrite (closes #1415, #1416)

---

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java

Add SSL error handling, based on changes from PR #668 by @eahrold. Fixes security issues in apps which depend on `onError` being emitted for non-successful page loads, including SSL errors.
Navigations are cancelled and error is shown to user by default. No option is given to user to continue.
The only differences between PR #668 and this PR are:
* This PR excludes the unnecessary `SSL_MAX_ERROR` case, since it is never called per Android docs.
* This PR prefixes error descriptions with `SSL error:` to provide users and developers with more context, since some error messages do not provide sufficient context. Makes it more compatible with existing custom error screens too.
To quote the original PR:
> On android the JS `react-native-webview` WebView was not calling `onError` event or …

Add SSL error handling for Android WebView

---

docs/Guide.md

The link here: https://github.com/react-native-community/react-native-webview/blob/master/docs/Guide.md#managing-cookies is broken. Let's fix it.

[DOCS] Fix broken link in docs/Guide.md

---

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewModule.java

Issue fix for "Build is breaking for compileSdkVersion 28" - https://github.com/react-native-community/react-native-webview/issues/1437
https://github.com/react-native-community/react-native-webview/issues/1438
Tested by correcting plugin and running on Mobile
| Android |    ✅   |

support for compileSdkVersion=28

---

docs/Reference.md

[Demo](https://github.com/strdr4605/react-native-webview/blob/jump2header/docs/Reference.md#source)
Generated with:
```bash
jump2header --file Reference.md --slug "props-index" --start "source" --end "onFileDownload"
jump2header --file Reference.md --slug "methods-index" --start "extraNativeComponentConfig" --end "clearHistory"
```
If you don't like the PR but interested in links to top see [jump2header](https://github.com/strdr4605/jump2header#readme) for more options.
jump2header links will help for navigating it md file.

docs(reference): add links to top with jump2header

---

src/WebViewTypes.ts

**NOTE**: This is a complete clone of #1132 from @williamchong007! Please merge that instead! I'm not trying to take credit, just trying to get this fixed since that PR was auto-closed by the bot despite being a simple and straightforward fix.
In Typescript, using applicationNameForUserAgent in <WebView> throws a type error
```Property 'applicationNameForUserAgent' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<WebView> & Readonly<WebViewProps> & Readonly<{ children?: ReactNode; }>'.```
This is because #707 moved the type definition from `WebViewSharedProps` to `CommonNativeWebViewProps`. We should define the type in both interfaces.
Tested setting the property. Ran `yarn ci`.
| Android | …

fix(types): Add missing applicationNameForUserAgent type in WebViewSharedProps

---

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java
android/src/main/java/com/reactnativecommunity/webview/events/TopCrashEvent.kt
android/src/main/java/com/reactnativecommunity/webview/events/TopRenderProcessGoneEvent.kt
docs/Reference.md
src/WebView.android.tsx
src/WebViewTypes.ts

On Android, the WebView process may get killed/crash. When this happens, if not handled appropriately, the whole app gets terminated in a quite brutal way (not even error reporting frameworks seemed to report this crash).
The fix: implement a handler for `onRenderProcessGone` (SDK >= 26) and return `true`.
The implementation also adds a new `onCrash` event so a webview crash can be handled on user land.
TODO: Review implementation for iOS, although it is most likely not needed.
Tested on Motorola G5 and Google Pixel 2
Device / simulator
Test a webview that may run out of memory or render a extremely large image.

feat(android): WebView crash handling

---

apple/RNCWebView.h
apple/RNCWebView.m
apple/RNCWebViewManager.m
docs/Reference.md
src/WebViewTypes.ts

This allows overriding iPadOS 13's desktop-class browsing to load mobile content instead of desktop content (or requesting desktop content on a phone). Briefly described [here](https://sourcegraph.com/github.com/WebKit/webkit/-/blob/Source/WebKit/UIProcess/API/Cocoa/WKWebpagePreferences.h#L30:41) and in the WWDC19 session [Introducing Desktop-class Browsing on iPad](https://developer.apple.com/videos/play/wwdc2019/203/) 
Note that while it is technically possible to dynamically request different content modes via `decidePolicyForNavigationAction`, this change only sets the content mode via `setUpWkWebViewConfig`.
Tested changing the property and loading different content types. Ran `yarn ci`.

Add iOS contentMode property

---

docs/Debugging.md

I do `react-native-webview` debugging pretty infrequently, so when I don't see my simulator in the Develop menu, I forget to try restarting Safari. Twice now it's been the fix, and if this PR gets merged I won't waste time trying to figure this out next time!
Worked on my machine :-)
Nothing - just a doc update
| Android |    N/A     |

Add a debugging note

---

android/src/main/java/com/reactnativecommunity/webview/events/TopShouldStartLoadWithRequestEvent.kt
apple/RNCWebView.m
docs/Reference.md
src/WebViewShared.tsx
src/WebViewTypes.ts

`onLoadingStart` is not raised for inner frames, but `onShouldStartLoadWithRequest` still is on iOS. This keeps that behavior but adds `isTopFrame` to `onShouldStartLoadWithRequest` so that apps can perform their own filtering if desired. Android does not have that behavior but `isTopFrame` is still present and hardcoded to `true` for API consistency.
Ran `yarn ci`. Tested with an app loading pages with inner frames.
I'm a bit fuzzy on the type naming patterns (e.g. `WebViewNavigation` vs `WebViewNavigationEvent`) so open to feedback there.

feat(events): Add isTopFrame to shouldStartLoadForRequest

---

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java
docs/Reference.md
src/WebView.android.tsx
src/WebViewTypes.ts

This PR is to add a new React prop, `androidLayerType`, that allows [setting the layer type](https://developer.android.com/reference/android/view/View#setLayerType(int,%20android.graphics.Paint)) for Android using props. It also deprecates `androidHardwareAccelerationDisabled` prop, as the use of both of them at the same time might cause undefined behaviour.
**Motivation:**
The general motivation is to be able to control the layer type through props.
It would also solve the problem of rendering big pieces of HTML in a WebView when the hardware acceleration is disabled.
When we use HA, all drawing operations that are performed on a View's canvas use the GPU, so the layer is set to LAYER_TYPE_HARDWARE. Disabling HA means setting the view to LAYER_TYPE_SOFTWARE, which uses a drawing cache …

feat(android): Add androidLayerType as prop

---

src/WebViewTypes.ts

`ContentInsetAdjustmentBehavior` was originally added as a string union type (https://github.com/react-native-community/react-native-webview/pull/730). The change to support MacOS (https://github.com/react-native-community/react-native-webview/pull/1164) replaced it with an enum (https://github.com/react-native-community/react-native-webview/pull/1164/files#diff-bad447a30759e328812e9bae6798621cR269), which was a breaking change, especially as the enum was not exported from the main library. Exporting the enum would probably also help, but since this was the only enum and the rest of `react-native-webview` uses string unions instead, it seems best to revert it to a string union.
The `ContentInsetAdjustmentBehavior` prop can now once again be simply set to a string value like "always." …

Convert ContentInsetAdjustmentBehavior from an enum back to a string union type

---

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java
android/src/main/java/com/reactnativecommunity/webview/RNCWebViewModule.java
src/WebView.android.tsx

*This is a re-imagining of #1479. #1479 had some ABI issues that could only be solved by backporting react-native patches and using NDK r21, which we believe actually exploited a compiler bug. This PR does not have any such issues as it does not use JSI/JNI to accomplish its goals, but only pure Java. This will be much easier to maintain for the future.*
We (myself and @trcoffman) discovered a very interesting bug in our WebView app. Inside our app, there was a link that would HTTP redirect to a different origin, and then immediately manipulate history (to remove an authentication token from the URL and to navigate). This would cause the user to be stuck going back (you would go back and the history/location manipulation would happen again). The only way to get back was to tap the back …

feat(android): Synchronous onShouldStartLoadWithRequest

---

index.d.ts

Declare WebView class as a generic class.
Without declaring as a generic class, it will not be possible to do the following (extending WebView with generic):
``` javascript
interface SubWebViewProps extends WebViewProps {}
default class SubWebView extends WebView<SubWebViewProps> {}
```
"Type WebView is not generic." 
Modified Typescript defination file only.

Fix(types): Update Typescript definition file, declaring WebView class as a generic class

---

docs/Reference.md

Now that onNavigationStateChange supports hash url changes in 8.x, we should probably remove this footer note to avoid any confusion, since the intercepting hash url changes portion has been removed from the linked guide.
n/a
n/a
n/a
n/a
n/a

chore(docs): remove hash url change note

---

react-native-webview.podspec

Latest Xcode 12 fails to build while without a module to depend on `React-Core` directly hence this change is necessary for all native modules on iOS. For more details please check: https://github.com/facebook/react-native/issues/29633#issuecomment-694187116
Use this branch to install with an app running on Xcode 12.

fix: Xcode 12 compatibility

---

apple/RNCWebView.h
apple/RNCWebView.m

In the past couple weeks, a new feature was added to allow for pull to refresh support. This was implemented using a UIRefreshControl which breaks the support for react-native-macos as macOS does not have access to that library. I have moved functions relating to pull to refresh to be inside an if the target is not macOS so that it can compile on macOS.
Nothing has changed to the library except it now can compile again in a react-native-macos project. I created a project, added the dependency, fixed these things and it worked again. No code was added, just platform conditionals were added.
| macOS     |    ✅     |

fix(macOS): Don't include iOS pull-to-refresh control

---

docs/Reference.md

This is a gotcha that's gotten me more than once. `onMessage` is a required parameter _if_ you're injecting javascript.

update injectedJavascript ios docs

---

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java

Fixes issue introduced in PR #1450.
This PR updates the SSL error handling to call onReceivedError() only on top-level navigations.
This prevents iframes and other subresources from causing user-visible SSL error messages. The desired behavior is only to have top-level navigations show user-visible error messages. All other requests should be cancelled automatically with no user-visible error message.
Use any basic React Native WebView app (I have a PoC app I use to generally test RNWV behavior.)
1. Navigate the top-level window to https://aogarantiza.com/react/webview-ssl-error-test.html
2. Tap the link in the iframe.
Observed behavior due to #1450: iframe navigation is cancelled but user-visible error is shown which covers the full page, making it seem like a top-level navigation issue. …

fix(android): Update SSL error handling

---

windows/ReactNativeWebView/ReactNativeWebView.vcxproj

Fix error produced when module is added to a React Native app and run in Windows emulator.
Error reads: "The target "Deploy" does not exist in the project".
Test Plan:
Create a React Native Windows app.
Add datetimepicker module to app via `yarn add`.
Run `npx react-native run-windows`.
If app deploys successfully and loads in the Windows emulator, the code change has succeeded.

Resolve Missing Deploy Target

---

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java

Fixes memory leak reported in #1047 
`RNCWebViewManager` holds a reference to `RNCWebChromeClient`, which maintains a reference to `ReactContext`. PR clears the reference to `RNCWebChromeClient` on cleanup/destroy, to ensure the reference is not retained.
Leak canary report:

Ensure WebChromeClient reference cleared on destroy to fix memory leak

---

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java
docs/Reference.md
example/App.tsx
example/examples/NativeWebpage.tsx
src/WebView.android.tsx
src/WebViewTypes.ts

Hey folks 👋
This PR wants to introduce the recommended mitigation for CVE-2020-6506 as indicated [in the blogpost](https://alesandroortiz.com/articles/uxss-android-webview-cve-2020-6506#potential-mitigations) by the security researcher who disclosed it.
> Enable multiwindow support. If needed, implementation options exist to mimic single-window behavior and minimize breaking changes. Does not require multi-tab UI. Suitable for browsers and frameworks.
The final code that you see here is, basically, a mix my brain plus the following links:
* https://github.com/react-native-webview/react-native-webview/pull/1663
* https://github.com/flutter/plugins/pull/2991
* [setSupportMultipleWindows](https://developer.android.com/reference/android/webkit/WebSettings#setSupportMultipleWindows(boolean))
* …

Introduce mitigations for CVE-2020-6506

---

docs/Reference.md
src/WebViewTypes.ts

Fixes type of the event of the `onScroll` function.
Issue: #1627

Fix onScroll event type

---

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewModule.java

Fix for issue https://github.com/react-native-webview/react-native-webview/issues/1661. onShouldStartLoadWithRequest is not called on first load on Android because the first lockIdentifier value is 0, but the callback is only invoked if lockIdentifier is truthy.

Fixes onShouldStartLoadWithRequest not called on first load on Android.

---

apple/RNCWebView.m

This PR fixes the shared cookie handling for iOS <= 10 when the request is `nil`.
This would otherwise end in a `EXC_BAD_ACCESS` crash.

fix(iOS): restore cookie handling for iOS <= 10

---

apple/RNCWebView.h
apple/RNCWebView.m
apple/RNCWebViewManager.m
docs/Reference.md
src/WebViewTypes.ts

This is a PR to update the library to include the property allowUniversalAccessFromFileURL to iOS and macOS also.
Also, with this PR, some updates were made in the type definition file to include the new property for macOs and iOS but also to add a property that was missing (allowFileAccessFromFileURLs)
Issue: #1290

allowUniversalAccessFromFileURLs property to iOS and macOS

---

windows/WebViewBridgeComponent/WebViewBridgeComponent.vcxproj

When module is added to a React Native Windows app and the app is run, an error appears saying that it is missing a "Deploy" target for the module. This issue resolves itself on modules built with RNW 0.63+. Bug was fixed for ReactNativeWebView project [here](https://github.com/react-native-webview/react-native-webview/pull/1716). This fixes the same issue occurring with the WebViewBridgeComponent project.

Resolve Deploy Issue

---

apple/RNCWebView.m
package.json

To attach cookie with all resource requests for the page loaded
**Summary**
- This PR solves this feature request #1875
- Issue: Currently, the cookies are added for page load request if custom cookies are passed in the webview source headers but they are not added for resource requests.
- How did you implement the solution?
I implemented this solution by adding cookies in webview configuration so that cookies will be send in resource requests as well.
- What areas of the library does it impact?
RNCWebView

 [iOS] Send cookies with resource requests

---

apple/RNCWebView.m

When close the webview, dealloc function does not execute, there have a retain cycle in RNCWebView.m file
NO
Hit berakpoint in dealloc function，after the webview close，this function is not excute

fix(iOS): webview memory leak

---

docs/Reference.md

These properties are either wrong or undefined for Android. I'll make a separate PR to try to include the [`hasGesture`](https://developer.android.com/reference/android/webkit/WebResourceRequest#hasGesture()) property which is similar to `navigationType == click` for Android.

chore(docs): Clarify that navigationType and isTopFrame is iOS only

---

apple/RNCWebView.h
apple/RNCWebView.m

When compiling pods for my app, I get the following warnings:
```
/my_project/node_modules/react-native-webview/apple/RNCWebView.h:23:29: Pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified)
my_project/node_modules/react-native-webview/apple/RNCWebView.h:24:4: Pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified)
/my_project/node_modules/react-native-webview/apple/RNCWebView.m:1031:61: '&&' within '||'
```
I've added the missing nullability specifiers to silence the warnings, and I updated the error code test to test the domain only once.

fix(ios): Add missing nullability specifiers; fix if block warning

---

apple/RNCWebView.h
apple/RNCWebView.m
apple/RNCWebViewManager.m
docs/Reference.md
src/WebViewTypes.ts

iOS 14 introduces the support for App Bound Domains, which are necessary to access several privacy- and security-related features.
I would like to add the support for `limitsNavigationsToAppBoundDomains` prop.
Context: https://webkit.org/blog/10882/app-bound-domains/
OS | Implemented
-- | :--:
iOS | ✅
Android | ❌

Add support for iOS-specific prop `limitsNavigationsToAppBoundDomains`

---

windows/ReactNativeWebView.sln
windows/ReactNativeWebView/ReactNativeWebView.vcxproj
windows/ReactNativeWebView/ReactWebView.cpp
windows/WebViewBridgeComponent/WebViewBridgeComponent.vcxproj

Fixes #1856 
The `FrameworkElement` API `IsLoaded` is only available on 17763 and up, attempts to call it on older OS releases will crash.

Check UAP contract version before calling FrameworkElement.IsLoaded

---

docs/Getting-Started.md

Due to current constraints in RNW, perspective must be disabled in RNW apps in order for WebView components to be scrollable with touch. Documented that note to prevent future developers running into this issue. Ultimate goal is to enable perspective settings requirements for modules so that altering app settings to access touch scroll functionality with not be necessary.

Update Docs with Instructions for Windows WebView Scrolling

---

package.json

Need to add react-native.config.js to files list in root package.json in order for file to be published and thus for autolinking for Windows to work.
Resolves https://github.com/microsoft/react-native-windows/issues/7758

Add react-native.config.js to Published Files

---

package.json

Reverts react-native-webview/react-native-webview#1985
File specified is incorrect. Uncaught typo. Should be react-native.config.js instead. New PR on the way.

Revert "Add react-native.config.js to Published Files"

---

package.json

Need to add react-native.config.js to files list in root package.json in order for file to be published and thus for autolinking for Windows to work.
Resolves microsoft/react-native-windows#7758

Add react-native.config.js to npm Publish

---

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java

**Issue tackled:** Currently, Android permissions have to be requested before the instantiation of the webview. In this new implementation, Android permissions are requested "on the fly" when the webview needs it. It is, in some ways, a mapping of the webview permissions to the native Android permissions.
A react native webview with following code:
```javascript 
navigator.getUserMedia({ video: true, audio: true }, () => { console.log('video/audio success') }, console.error);
navigator.geolocation.getCurrentPosition(console.log, console.error);
```
And in the AndroidManifest.xml:
```xml
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
<uses-permission android:name="android.permission.CAMERA" />
<uses-permission android:name="android.permission.RECORD_AUDIO" /> …
```

(Android) Enhanced camera/audio and geolocation permissions

---

apple/RNCWebView.h
apple/RNCWebView.m
apple/RNCWebViewManager.m
docs/Reference.md
example/App.tsx
example/examples/ApplePay.tsx
src/WebViewTypes.ts

Add new prop `enableApplePay` for ios which disables script injection and allow Websites to invoke Apple Pay api.
This comes with a cost features like script injection,html5 History , shared Cookies, atEndScript , atStartScript will not work
[Apple Documentation](https://developer.apple.com/documentation/safari-release-notes/safari-13-release-notes#Payment-Request-API). We can still use postMessage provided  `window.postMessage` wont work `window.webkit.messageHandlers.ReactNativeWebView.postMessage` will work
possible fix for #920

Apple Pay support in iOS

---

react-native.config.js

Fix an issue for non windows, such as on mac for ios or android builds.
When doing a `pod install` on mac, the error below occurs.
When building for android, the same error occurs.
This is because the way react-native-cli still reads/parses the react-native.config.js file EVEN if it's not actually going to do anything with it. In other words, it doesn't do a lazy read.
I've let the other appropriate teams know for longer term. But in interim, this will fix it for non windows, and it doesn't break windows since windows is perfectly happy with / or \ or \\\
The underlying error.
```
error ENOENT: no such file or directory, open '/Users/namrog84/MyRepo/src/apps/MyApp/node_modules/react-native-webview/windows/ReactNativeWebView\ReactNativeWebView.vcxproj'. Run CLI with --verbose flag for more …
```

Fix / in react-native.config.js for non windows platforms.

---

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java
docs/Reference.md
src/WebView.android.tsx
src/WebViewTypes.ts

Currently, on Android, it is not possible to scroll inside a webview when the webview is itself placed inside a scrollview.
This behaviour is documented in this issue : https://github.com/react-native-webview/react-native-webview/issues/1568
On iOS, this behaviour is already handled.
The purpose of this PR is to add an android prop that enable the "nested" scroll inside the webview. 
There is a counterpart though : when the prop is set to `true`, the user has to scroll outside the webview to effectively scroll the scrollview, since the native event is now handled by the webview.

feat: add prop to allow nested scroll on android

---

apple/RNCWebView.m
apple/RNCWebViewManager.m

Make it so that if you change the userAgent prop, this change is propagated to
the native webview on iOS/macOS. Android already has this functionality.
Sometimes it is useful for WebView apps to be able to change their user agent
dynamically to communicate custom things to the web app they are hosting.
Since we can't add custom headers to every single request made by the webview,
the user agent can be used to send things like feature flags to the web app, so
it can have the appropriate behavior depending on what state the mobile app is
in.

feat(apple): userAgent can be changed at runtime

---

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java
docs/Reference.md
src/WebView.android.tsx
src/WebViewTypes.ts

Enables props to control pinch to zoom, a required feature for kiosk environments.
Mentions #1649

feat(android): add props to control pinch to zoom and internal zoom controls

---

package.json

Fixes #1935
I've tested and it works just fine on 0.64.x

Remove upper bound on React Native peerdep

---

docs/Debugging.md

It took time for me to open remote debug window on chromium.
How about to change like this with a reference link?

Update explanation to open remote debug window

---

android/build.gradle
android/gradle.properties
android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java
docs/Reference.md
src/WebViewTypes.ts

On iOS the WebView automatically uses the dark-theme if the system appearance is set to dark. On Android this is not happening.
This PR adds support for dark-theme, and fixes #1677 (this issue was closed because stale).

Support dark mode on Android

---

android/build.gradle
android/gradle.properties
example/android/build.gradle
package.json
yarn.lock

Builds will no longer be able to resolve artifacts from JCenter after February 1st, 2022 because jcenter servers shut down
so, i remove jcenter and update react-native (since 0.65.1 they don't use jcenter)

fix(jcenter): remove jcenter

---

src/WebViewTypes.ts

It seems we have missing types for [ignoreSilentHardwareSwitch](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#ignoreSilentHardwareSwitch). Added it in
https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#ignoreSilentHardwareSwitch
https://github.com/react-native-webview/react-native-webview/blob/master/docs/Guide.md#hardware-silence-switch

fix(types): add missing ignoreSilentHardwareSwitch prop

---

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java
apple/RNCWebView.h
apple/RNCWebView.m
apple/RNCWebViewManager.m
docs/Reference.md
src/WebViewTypes.ts

I have created a PR that supports basic authentication. This allows to use the `basicAuthCredential` property to pass in a `username` and `password` to use for basic authentication.
**Related Issues**
#18
**Solution**
On iOS, within the existing `didReceiveAuthenticationChallenge` delegate method, I added handling for the type `NSURLAuthenticationMethodHTTPBasic`.
On Android, I have overridden the `onReceivedHttpAuthRequest` callback method.
**Impact**
Since I added new code, I think it will have little impact on existing code.
I checked the operation on iPhone 7 (iOS 13.5.1) and Pixel 3a (Android 11-beta1).
| iOS     |    ✅    |
| Android |    ✅    |

Basic Authentication Support

---

apple/RNCWebView.m

As the gesture recognizer & long press is not available on macOS and lead to build errors I added ``#if !TARGET_OS_OSX`` to the ``gestureRecognizer``, ``startLongPress`` and the ``didMoveToWindow`` handler

Fix: macos gesture recognizer & long press

---

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java

This PR adds a null-pointer check for `reactContext.getCurrentActivity()` before creating the `RNCWebChromeClient` with full-screen video support.
When `reactContext.getCurrentActivity()` is `null`, the `RNCWebChromeClient` will be initialized without full-screen video support.
Closes #1406.
Closes #2190.

fix(android): add null-pointer check for `activity` before creating `RNCWebChromeClient` (closes #1406, #2190)

---

apple/RNCWebView.h
apple/RNCWebView.m
apple/RNCWebViewManager.m
docs/Reference.md
src/WebViewTypes.ts

Referencing issue #2256 
**Problem:** By default, iOS quickly forgets about permissions granted to requests originating from `WKWebView`. Every time the user relaunches the app and performs an action within WKWebView such as turning on their microphone or camera, `WKWebView` asks for their permission. What's more, when `WKWebView` initiates a permission request, iOS will prompt twice: Once for the native layer, and once for the website loaded within `WKWebView`. 
We wanted our WebRTC-based audio & video communications app to be kind to users and remember their preferences instead of bothering them each time with repetitive prompts. Also, we wanted to get rid of the double-prompt issue. The second prompt related to the loaded website was especially irritating because it displayed long URLs …

Enhanced permissions handling to prevent repetitive prompts #2256

---

.github/workflows/windows-ci.yml

CI started to fail as some minor version update of a dependency started to require a higher version of node than we were using (12.9.1):
```
yarn install v1.22.17
[1/4] Resolving packages...
[2/4] Fetching packages...
error @jest/create-cache-key-function@27.3.1: The engine "node" is incompatible with this module. Expected version "^10.13.0 || ^12.13.0 || ^14.15.0 || >=15.0.0". Got "12.9.1"
error Found incompatible module.
```

chore: Update node version in CI to 14

---

apple/RNCWebView.m

macOS fails to build because `_mediaCapturePermissionGrantType` is defined only for iOS:
https://github.com/react-native-webview/react-native-webview/blob/55b8a7702c82cc7b1713474daf6edf117f934d83/apple/RNCWebView.h#L95-L97

fix(macos): mediaCapturePermissionGrantType is iOS only

---

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java
docs/Reference.md
src/WebViewTypes.ts

Android WebView enforces a default minimum font size of 8 (see https://developer.android.com/reference/android/webkit/WebSettings#setMinimumFontSize(int)), causing scaling issues when using smaller font sizes. Content that may be deliberately scaled down to fit 100% width of the device may overflow. This property allows for customizing the minimum font size so scaling appears similar as on iOS.
In cases where grids of content/text are displayed (such as a seating chart), font size may need to be scaled down to fit the entire grid onto one screen width.
Previous Pull Request : https://github.com/react-native-webview/react-native-webview/pull/986
Running on Android.
Reference HTML code that uses font sizes < 8. 
For example:
`<WebView source={{ html: '<html><body><span style="font-size: …

feat(android): add minimum font size

---

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java

As discussed [here](https://github.com/react-native-webview/react-native-webview/pull/2323#issuecomment-1012654602), here's a `try/catch` implementation to mitigate [blob crashes](https://github.com/react-native-webview/react-native-webview/issues/1090), with the block restricted to the call site of the exception. Here's a video of the current behaviour. It **might** make sense to send a toast about the download being unsupported. Please let me know if you feel like that's desirable.
https://user-images.githubusercontent.com/8260207/149483121-5a31a03e-7d00-4b31-a9d2-a01249c5997b.mp4

Prevent crash from unsupported URI downloads

---

docs/Reference.md

We were logging every call to `onContentProcessDidTerminate` as an unexpected error on our app. 
Turns out it was completely expected to happen at some point. 
I added more details from [the Apple docs](https://developer.apple.com/documentation/webkit/wknavigationdelegate/1455639-webviewwebcontentprocessdidtermi) to make users aware that WKWebView live in completely different processes than the app. As such they are not included in the total RAM of the app, and can be terminated independently of the app to liberate some new apps.

docs: add more details on onContentProcessDidTerminate

---

index.d.ts

Closes #2361. Makes android-only methods possibly undefined properties on `WebView`.

Mark android-only methods as possibly undefined

---

metro.config.js
package.json
src/WebView.android.tsx
src/WebView.ios.tsx
src/WebView.macos.tsx
src/WebView.windows.tsx
src/WebViewNativeComponent.android.ts
src/WebViewNativeComponent.ios.ts
src/WebViewNativeComponent.macos.ts
src/WebViewNativeComponent.windows.ts
src/index.ts

This will allow developers to modify the TypeScript code and see changes without having to run `tsc --watch` separately.

chore: configure Metro to consume source directly

---

package.json
react-native.config.js
yarn.lock

fix: cannot find `react-native-test-app` when Metro starts

---

windows/ReactNativeWebView/ReactWebViewManager.cpp

fixes a type width warning when adding a size_t to an unsigned int

chore(windows): fix noisy warning

---

docs/Reference.md

I have noticed 3 other example used `={true}` syntax. 
1. Other examples used `={true}`, so I believed using this syntax is correct.
2. I also think it is much more beginner friendly.
There were no example for clearCache().
The *note* section seemed to be seperate from other explanation. 
I added a new line that was joined by other explanations.
It was also a bit hard to read when those two were connected.
The bactick for an example seemed to be missing. 
A whole section was shown as a code.

fix ex, add js ex, add line, add closing backtick

---

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java
android/src/main/java/com/reactnativecommunity/webview/RNCWebViewModule.java
docs/Reference.md
src/WebViewTypes.ts

Adding downloadMessage as a prop to react native web view so that the library consumer can specify the message shown in when downloading content.
Meant to address this issue: https://github.com/react-native-webview/react-native-webview/issues/2436
For our app, this allows the message to be localized (see the toast near the bottom):

Adding downloadMessage as a prop

---

apple/RNCWebView.h
apple/RNCWebView.m
apple/RNCWebViewManager.m

Previously, calling `.requestFocus()` would result in: 
This also allows consumers to mark the webview as the first responder, so that keyboard shortcuts, for example, can work right away as soon as the webview is loaded.

fix(ios): support requestFocus

---

src/WebView.tsx

Currently, the dummy WebView component render as very small red bordered box on unsupported platforms (look at upper left corner of the white render area):
I have added a short message to the empty so far View, and altered styling a bit. Border is removed, but the text will be red, so users can more easily spot the problem (if it occurs).
The package name (and capitalization) has been taken from the Readme file.
Running `yarn lint` do not yield any errors, example app is running as expected.

feat: improve dummy WebView 

---

README.md

Current note leads to an old blog post and mention old SDK.
Replace the note with an additional entry to the supported platforms list.

chore(readme): update Expo in supported platforms section

---

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewModule.java

Fixes #2428.
This is based on @karthikiyengar's previous fix in #2328.
If desired, I could also include the tweaks in my [test branch](https://github.com/TheAlmightyBob/react-native-webview/tree/test) for reproing the issue in the example app.... however, since it is an _example_ app and not a _bug regression test_ app, I'm not sure that would be appropriate.

Don't crash if trying to download "invalid" URIs on Android

---

docs/Custom-Android.md
docs/Custom-Android.portuguese.md

Fix the "register the module" link in the Custom Android doc

---

android/gradle.properties

Fixes the error "Module was compiled with an incompatible version of Kotlin" #2578

fix(android): bump up kotlinVersion to 1.6.0

---

apple/RNCWebView.m

There are cases - albeit seldom - where mainDocumentURL in request is nil hence causing a crash when attempting to add it to the event object i.e [event addEntriesFromDictionary]. 
Here is the crash we were encountering: 
```
Fatal Exception: NSInvalidArgumentException
*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[1]
```
This PR aims to solve the issue.
Related issue: [2442](https://github.com/react-native-webview/react-native-webview/pull/2442)

add null check safety for adding mainDocumentURL to event

---

docs/Reference.md
docs/Reference.portuguese.md
src/WebViewTypes.ts

This PR adds two new information tables to the following sections in the Reference.portuguese.md and in the Reference.md:
- menuItems
- onCustomMenuItemSelection
These features are currently only available on iOS which was discussed in some issues and pull requests already:
- #2523 
- #2522 
Currently there is no documentation that says that this feature is only available on iOS. As long there is no feature parity this should be stated in the documentation.

fix(docs): Add information that custom menu items are only available for iOS

---

apple/RNCWebView.m

Use a `WKHTTPCookieStoreObserver` to sync the cookies from the webview to `NSHTTPCookieStorage`.
Most developers shouldn't notice any difference in behaviour but based on my testing this seems to be more reliable than the old way where the cookies were synced in the `didFinishNavigation` callback. This also fixes a race condition bug that we hit with our production app.

Cookie sync improvements

---

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java
docs/Reference.md
src/WebViewTypes.ts

Add a new prop : allowsProtectedMedia to grant `android.webkit.resource.RESOURCE_PROTECTED_MEDIA_ID` permission to webview if set to true.
With the current implementation, Android WebViews can't play any media protected by DRM because the permission is not handled properly.
I propose an implementation where the developer can decide whether or not to allow it using a react prop `allowsProtectedMedia`. The default value is false.
The end user is not warned about this, I leave this responsibility to the developer. I believe this is acceptable as even applications such as Chrome Android do not ask for user permission, they are granted by default.
N.B: I haven't tackled the `RESOURCE_MIDI_SYSEX` permission as I don't have the proper setup to test it.
Also if this approach were to be accepted, …

feat(Android): Handle RESOURCE_PROTECTED_MEDIA_ID permission

---

apple/RNCWebView.m
docs/Guide.md
example/App.tsx

Support File Input On MacOS #2633, by implementing https://developer.apple.com/documentation/webkit/wkopenpanelparameters?language=objc
This requires `User Selected File` read permission otherwise will crash when attempting to open file input

Support File Input On Macos

---

src/WebView.android.tsx
src/WebView.ios.tsx
src/WebView.macos.tsx
src/WebView.windows.tsx

This was always being set to `true`, even if no `onMessage` handler was provided. At the point that `messagingEnabled` is set, `onMessage` actually refers to a wrapper callback from `WebViewShared`, which is always defined, not the actual `onMessage` handler that was provided (or not) by the application.
This regressed in version 11.22.0
Thanks to @Ldoppea for indirectly bringing this to my attention. 😁

fix(js): messagingEnabled prop

---

docs/Contributing.md

For the "Testing in a new `react-native init` project" section, manual linking is no longer necessary, and added notes about possible errors and need to remove a duplicate/conflicting copy of React
(I don't think this is actually specific to the new architecture branch, I just figured it might be simpler for rebasing/etc if I just targeted that.. I'm fine with waiting 'til that goes in first and then retargeting this to main)

[NewArchBranch] Update Contributing doc

---

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManagerImpl.kt
android/src/oldarch/com/reactnativecommunity/webview/RNCWebViewManager.java
docs/Custom-Android.md

@Titozzz 
(as I said on Slack, I'm open to better ideas, but this seemed like the simplest way to get things working again)

[NewArchBranch] Allow passing a custom RNCWebView subclass to RNCWebViewManager's createViewInstance (old architecture only)

---

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManagerImpl.kt
android/src/main/java/com/reactnativecommunity/webview/RNCWebViewModuleImpl.java

We ran into an issue where react-native-webview crashed on Android 13 while downloading a file with the "%" character in its name. It is similar to https://github.com/react-native-webview/react-native-webview/issues/2428, but the fix in v11.22.2 does not prevent the crash because the exception being thrown is different. Here is the stack trace:
`Fatal Exception: java.lang.SecurityException: java.io.IOException: Invalid file path
at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
at android.os.Parcel.createException(Parcel.java:2995)
at android.os.Parcel.readException(Parcel.java:2978)
at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
at …

fix(Android): Don't crash while downloading file with % in filename

---

windows/ReactNativeWebView/ReactNativeWebView.vcxproj

In RNW .72, we bump WinUI from 2.7 to 2.8 which targets a higher TargetPlatformMinVersion. This PR bumps the WindowsTargetPlatformMinVersion to the correct version for RNW .72

fix(windows): bump WindowsTargetPlatformMinVersion 

---

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewClient.java

This is the same fix as #2598. I have just rebased `master`.
@matinzd Please review.
Fixes: 
- https://github.com/react-native-webview/react-native-webview/issues/24
Reference: https://github.com/react-native-webview/react-native-webview/pull/2598
Credits to [bobsmits](https://github.com/bobsmits)

fix(android): make history.pushState changes trackable on android

---

apple/RNCWebViewImpl.m

After this [commit](https://github.com/react-native-webview/react-native-webview/commit/40c98078939d486d95c27ce83bb2f378e1d13dd6), the macOS WebView was broken because react-native-macos does not support the didMoveToSuperview [functionality](https://github.com/microsoft/react-native-macos/blob/main/React/Base/RCTUIKit.h#L388).

fix(issue #3001 )

---

apple/RNCWebViewImpl.m

Fixes multiple issues with the iOS new architecture (WebViews failing to render, #3003, possibly more) and occasional crash with the iOS old architecture.
Re: the crashes on old architecture - I don't know the exact reason for this, but I saw the test app crash with EXC_BAD_ACCESS frequently before this change and am unable to repro the crash after the change.
Re: new architecture issues - I don't know the details, but the new architecture rarely calls `didMoveToSuperview`, so initialization code was simply never getting executed. It still calls `didMoveToWindow`. An example of the "WebViews failing to render" is that, if you run the test app, the WebView will initially display, but then if you switch to a different test, or tap "simulate restart," or refresh React Native via cmd+R/etc, …

fix: Revert to didMoveToWindow #2930

---

docs/Guide.md

The static server package does not seem to work in the later version of React Native. Or, there's a way to make it work but not discussed.  A [fork](https://github.com/birdofpreyru/react-native-static-server) of the library works as expected.  While it may not have many 'stars' the fact that it works and is also maintained, makes it a more suitable candidate.

Update Guide.md to link a working static server package

---

docs/Reference.md
docs/Reference.portuguese.md
src/WebViewTypes.ts

---
- Update reference documentation for `menuItems` and `onCustomMenuSelection` props, to reflect the changes made to it in Release [v12.3.0](https://github.com/react-native-webview/react-native-webview/releases/tag/v12.3.0). <br><br>The changes are described in #2610

Reference documentation updates for menuItems

---

docs/Debugging.md

A new `webviewDebuggingEnabled` prop has been added in https://github.com/react-native-webview/react-native-webview/pull/2937. However, the debugging instructions were still mentioning the old ways:
- Android: `setWebContentsDebuggingEnabled`
- iOS: not working on iOS 16.4+
I updated the relevant parts of the instructions to mention the new prop.

Update debugging instructions

---

.github/workflows/macos-ci.yml
example/ios/Podfile.lock
example/macos/Podfile.lock
package.json
yarn.lock

- Bumped `react-native` to 0.71.12
- Bumped `react-native-macos` to 0.71.33
- Bumped `react-native-test-app` to 2.5.15
- Bumped `react-native-windows` to 0.71.30
- Updated `resolutions` field in `package.json`
- Removed workaround for adding react-native-macos@0.68
- Deduped `yarn.lock`
```
pod install --project-directory=example/macos
yarn macos
yarn start
```
| Android | iOS | macOS |
| :-: | :-: | :-: |
| ![Screenshot_1692192014](https://github.com/react-native-webview/react-native-webview/assets/4123478/e1a447ba-441f-4750-ad9e-c446d17ac5cd) | ![image](https://github.com/react-native-webview/react-native-webview/assets/4123478/c4db976d-438d-4245-ba33-6b4760d10d56) | ![image](https://github.com/react-native-webview/react-native-webview/assets/4123478/12c44f3f-8524-48cf-81ca-31c8580ba330) …

chore: bump react-native-macos to 0.71

---

android/src/newarch/com/reactnativecommunity/webview/RNCWebViewManager.java
apple/RNCWebView.mm
apple/RNCWebViewImpl.h
apple/RNCWebViewImpl.m
apple/RNCWebViewManager.mm
docs/Reference.md
example/App.tsx
example/examples/Suppress.tsx
src/RNCWebViewNativeComponent.ts
src/WebViewTypes.ts

This is a followup on https://github.com/react-native-webview/react-native-webview/pull/2845
Implemented the `suppressMenuItems` prop (iOS only) to suppress menu items from the long press context menu.

Suppress menu items

---

apple/RNCWebViewImpl.h
apple/RNCWebViewImpl.m
apple/RNCWebViewManager.mm
docs/Reference.md
example/App.tsx
example/examples/ClearData.tsx
example/ios/Podfile.lock
src/WebViewTypes.ts
yarn.lock

Issues arise where it's necessary to clear web caches and storage. This makes the API complete by adding the ability to clear the cache on iOS (which was previously only supported on Android).
These changes are very similar to #1270 and #1465 (both closed no merge) but updated to account for the recent new arch and codebase structure changes.
Below you can see a demonstration using the example app. 
In this first video, you can see the font assets being loaded from memory in the simple reload, then when cache is cleared, you can see the same assets being loaded over the wire. 
https://share.cleanshot.com/1xBTWLf8
In the second video, you can see I've added an entry in local storage. When I perform the clearCache action, you can see that entry is removed. …

Add clearCache method on iOS

---

docs/Reference.md

I neglected to add a link to the new section in my original PR.

Add InjectedJavaScriptObject link in Reference.md

---

android/src/main/java/com/reactnativecommunity/webview/RNCWebChromeClient.java
android/src/main/java/com/reactnativecommunity/webview/RNCWebView.java
android/src/main/java/com/reactnativecommunity/webview/RNCWebViewClient.java
android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManagerImpl.kt
android/src/main/java/com/reactnativecommunity/webview/RNCWebViewWrapper.kt
android/src/newarch/com/reactnativecommunity/webview/RNCWebViewManager.java
android/src/oldarch/com/reactnativecommunity/webview/RNCWebViewManager.java

possible solution for #2771
observations:
- the crash is from https://android.googlesource.com/platform/frameworks/base/+/f05f9b960832b6272b6740721c0a4bbd1ce632c1/libs/hwui/pipeline/skia/GLFunctorDrawable.cpp#95 which looks like for WebView to draw something on offscreen buffer because it hits the view boundary.
- the `MakeRenderTarget()` returns null because ~SK_SUPPORT_GPU is undefined in skia build.~ the offscreen surface size is 0, i.e. `!imageInfo.width() || !imageInfo.height()`  I could confirm it returns null by attaching debugger. https://android.googlesource.com/platform/external/skia/+/be52e9ba4d0a3c1e27c2ac215ddb14ab2b72274b/include/core/SkSurface.h#337
- modern devices should use skia vulkan (skiavk) renderer for hwui. supposedly it will not crash.  i.e. `adb shell getprop …

fix(android): Prevent libhwui crash when WebView is in ScrollView

---

package.json

Fix https://github.com/reactwg/react-native-releases/discussions/64#discussioncomment-7197584
According to:
- [Metro docs](https://facebook.github.io/metro/docs/package-exports#example-use-conditional-exports-to-target-web-and-react-native)
- [Template of `create-react-native-library`](https://github.com/callstack/react-native-builder-bob/blob/main/packages/create-react-native-library/templates/common/%24package.json#L8)
Libraries should set the field `"react-native"` in `package.json`, so that Metro will correctly resolve the main entry for platform React Native.
Not adding this field will cause the library to be incompatible with RN 73, as RN 73 enhanced requirements for `<FABRIC COMPONENT>NativeComponent` to be either flow-typed or a TypeScript source, and resolving this library from …

(fix): add field `"react-native"` to `package.json`

---

react-native-webview.podspec

This change updates the react-native-webview.podspec to consume the
`install_modules_dependencies` function provided by React Native to
configure the pods dependencies.
Thanks to using this function, whenever we update the function in React
Native, the library will automatically benefit from it.
This will make the library more future proof and more resilient to
changes in React Native.
This changes fixes building errors on new architecture on RN 0.72.

update podspec to use install_modules_dependencies

---

android/build.gradle

Upcoming react-native 0.73+ includes android gradle plugin 8+ which needs namespace in build.gradle but also needs buildFeatures.buildConfig enabled as well for modules that use it
It is not sufficient to enable this at the top-level app build.gradle, specific modules that use it (such as those that implement new architecture, it seems, or just directly use buildconfig like this one) must also enable it at the module level
This change was necessary and is in-use in my work app via patch-package as I work through android-gradle-plugin 8+ issues in prep for react-native 0.73 launching for everyone
This change is backwards compatible with android gradle plugin < 7, because it is in the same conditional as the namespace change which has similar backwards compatibility requirements
It is …

fix(android): add buildFeatures.buildConfig true for AGP8+ compat

---

android/build.gradle
react-native-webview.podspec

- when building on new architecture on RN 0.72 I've got a few build errors about some methods not being available on iOS 9.0, so I bumped the minimum iOS version on the new arch to 10.0
- I've also replaced the manually listed dependencies with `install_modules_dependencies` (see https://reactnative.dev/docs/new-architecture-library-ios#add-folly-and-other-dependencies, introduced in 0.71).
- I've removed the `react` block from `build.gradle`, since paths are set by default in RNGP (see https://github.com/facebook/react-native/blob/main/packages/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/ReactExtension.kt), and the rest is also declared in `codegenConfig` in `package.json`

Update new architecture config

---

windows/ReactNativeWebView/ReactWebView2.cpp

PR #3309 (https://github.com/react-native-webview/react-native-webview/pull/3309) introduced a bug whereby the call to create a web resource request would directly access the method property of the request object, however, in Typescript the method object is optional thus people that didn't include it implicitly experienced crashes due to the null reference.
- Refactor ReactWebView2.cpp to handle optional 'method' parameter

[Windows][WebView2] Refactor ReactWebView2.cpp to handle optional 'method' parameter

---

apple/RNCWebViewImpl.m

We had an issue with iOS and macOS where audio and video would continue playing after the WebView was unmounted, the only work around seems to be injecting JavaScript before unmounting, which isn't always easy or guaranteed
This issue has been reported a handful of times, such as in #2449
This PR fixes this issue by pausing all media playback in the webview destroy function

fix(ios, macos): Suspend media playback when destroying WebView on iOS/macOS

---

apple/RNCWebView.h
apple/RNCWebView.mm

Fixes https://github.com/react-native-webview/react-native-webview/issues/3295
Related https://github.com/microsoft/react-native-macos/issues/1534
**This pull request:** 
1. Substitutes **UIKit** with **RCTUIKit** to facilitate compatibility with **MacOS**, mostly using platform-specific conditional statements. Example:
```h
#if !TARGET_OS_OSX
#import <UIKit/UIKit.h>
#else
#import <React/RCTUIKit.h>
#endif // !TARGET_OS_OSX
```  
2. The `static_cast<bool>(` part of this PR fixes the error when building for Release:
```
Non-constant-expression cannot be narrowed from type 'BOOL' (aka 'signed char') to 'bool' in initializer list
```
It seems like implicit narrowing conversions not being allowed in C++11 braced initializer lists. In this initializer list, `bool` fields initialized `BOOL` …

Replace UIKit with RCTUIKit on MacOS for RCT_NEW_ARCH_ENABLED

---

android/src/oldarch/com/reactnativecommunity/webview/RNCWebViewManager.java
docs/Custom-Android.italian.md
docs/Custom-Android.md
docs/Custom-Android.portuguese.md

After #2874, unable to customize WebView on Android.
- Modify the `createViewInstance` argument for customization
- Update Custom-Android.md

fix(android): Fix WebViewManager can no longer be customized

---

android/src/main/java/com/reactnativecommunity/webview/RNCWebView.java
android/src/main/java/com/reactnativecommunity/webview/RNCWebViewClient.java
android/src/main/java/com/reactnativecommunity/webview/RNCWebViewMessagingModule.kt
src/NativeRNCWebView.ts
src/WebView.android.tsx

react-native-webview does not work on react-native 0.74 with bridgeless mode
there were two errors actually:
1. build error from override `shouldStartLoadWithLockIdentifier()`. the [newer codegen supports Int32](https://github.com/facebook/react-native/commit/ccd3b047709fda00123e8aec4294dce024b80244) and generates java code as int type. the current code is using double type. the pr tries to use double type as the implementation using double under the hood.
2.  on bridgeless mode, we cannot access `CatalystInstance`. it seems react-native-webview used it for sending direct message. BridgelessReactContext does not have equivalent `callFunction(moduleName: string, ...)`. this pr tries to register a single `RNCWebViewMessagingModule` module and check the underlying `messagingModuleName` …

fix(android): Fix bridgeless mode support

---

android/src/main/java/com/reactnativecommunity/webview/RNCWebView.java
android/src/main/java/com/reactnativecommunity/webview/RNCWebViewClient.java
android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManagerImpl.kt

Using `getJavaScriptContextHolder` on the `ReactContext` will result in a crash because the `catalystInstance` is null in bridgeless.  We should call it on the `ReactApplicationContext` which will use the `BridgelessReactContext` to return a valid `JavaScriptContextHolder`.
After the change, the issue is fixed and example app works as before.

Fix issue on bridgeless when accessing ReactContext

---

react-native.config.js

When running a build in a project without a **react-native.config.js** with the log in **metro.config.js** catch block:
```
FAILURE: Build failed with an exception.
* Where:
Script '/Users/brent/code/with-webview/node_modules/@react-native-community/cli-platform-android/native_modules.gradle' line: 442
* What went wrong:
A problem occurred evaluating script.
> Calling `[node, /Users/brent/code/with-webview/node_modules/@react-native-community/cli/build/bin.js, config]` finished with an exception. Error message: groovy.json.JsonException: Unable to determine the current character, it is not a string, number, array, or object
The current character read is 'H' with an int value of 72
Unable to determine the current character, it is not a string, number, array, or object
line number 1
index …
```

fix: Remove log statement that breaks react-native-community autolinking config

---

example/App.tsx
example/examples/MultiMessaging.tsx
example/examples/MultiMessaging.windows.tsx
src/WebView.android.tsx

Fixes #3368 which is my regression from #3352
JSModule `registerCallableModule()` does not support multiple listeners. The newer WebView will overwrite the previously registered callbacks.
This PR tries to move `registerCallableModule()` at top as a module singleton. With an intermediate EventEmitter to dispatch events to each WebViews. I tries to import the internal vendored EventEmitter from react-native. If that is not ideal, we could replace as third-party EventEmitter such as [fbemitter](https://www.npmjs.com/package/fbemitter).
extend the Messsaging.tsx example as two WebViews and check whether messages are sent correctly.
```tsx
import React, { Component } from 'react';
import { View, Alert, TextInput } from 'react-native';
import WebView from 'react-native-webview';
const HTML = …
```

fix(android): messaging regression for multiple webviews

---

apple/RNCWebViewImpl.m

fix(ios): Allow keyboard accessory view to be toggled after initialization using `hideKeyboardAccessoryView` prop

---

docs/Guide.italian.md
docs/Guide.md
docs/Guide.portuguese.md

As of v6.0.0, `react-native-community/cookies` was renamed to `react-native-cookies/cookies`: https://github.com/react-native-cookies/cookies?tab=readme-ov-file#important-notices--breaking-changes

Use latest react-native-cookies/cookies name in Guide.md

---

apple/RNCWebView.mm

**Context**
- The import should be prefixed w/ "React" in order for this to be built by Meta build system (BUCK).
- Examples:
- https://github.com/facebook/react-native/blob/03a51da727022d96f7f9bbc0840b1409121d0429/packages/react-native/React/Fabric/Mounting/ComponentViews/RCTFabricComponentsPlugins.h#L13
- https://github.com/software-mansion/react-native-svg/blob/9f6f6fd40c2cc4de2d117c24cf8a5c5e4bcfc4f9/apple/Shapes/RNSVGRect.mm#L14
- https://github.com/react-native-progress-view/progress-view/blob/f8d4555053120eea1e2b78df1e77cd1addd937bb/ios/Fabric/RNCProgressViewComponentView.mm#L11
- https://github.com/software-mansion/react-native-screens/blob/6b694e39b61865dd24ae7e90dcdbb2d69bda0f49/ios/RNSScreen.mm#L9
**Still builds!**

[fix][fabric][apple] Use correct header dir name in RCTFabricComponentsPlugins.h for BUCK compat

---

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManagerImpl.kt

Following the implementation of menuItems support in Android (#2993), there's been an observed issue within the Android platform where altering menuItems triggers a Null Pointer Exception.
This issue seems to originate from a missing null handling in `RNCWebViewManagerImpl.kt`. I've detailed the specific error encountered below for reference.
This PR introduces modifications to handle cases where value is null in the setMenuCustomItems function.
Your feedback is greatly appreciated.
```
com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'menuItems' of a view managed by: RNCWebView
at com.facebook.react.uimanager.v0$b.b(ViewManagerPropertyUpdater.java:123)
at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:79)
at …
```

fix(android): Handle null value in setMenuCustomItems method

---

apple/RNCWebViewImpl.m

During my recent work with react-native-webview, I encountered an issue with the postMessage function not functioning correctly on older iOS devices, notably iOS 13.7. 
Upon investigation, it became apparent that this issue stems from the WKUserScript initialization code changed in react-native-webview 13.8 (#3157)
Considering that iOS versions 13.7 and below do not support the Nullish coalescing assignment (??=) operator, I propose exploring alternatives to this operator for compatibility purposes. 
Your review and feedback on this matter would be greatly appreciated.
Thank you!

fix(iOS): replace nullish coalescing operator for older iOS versions

---

apple/RNCWebView.mm

Hey, at https://freeyourmusic.com we have a weird case, where user is redirected to a page with 404 error that crashes on iOS. After further investigation, we found that this is because of `description=NULL` as seen on screenshot:
This PR fixes this issue and possibly https://github.com/react-native-webview/react-native-webview/issues/3412

Fix crash when opening 4xx pages with no description.

---

apple/RNCWebView.mm
apple/RNCWebViewImpl.h
apple/RNCWebViewImpl.m
apple/RNCWebViewManager.mm
docs/Reference.italian.md
docs/Reference.md
docs/Reference.portuguese.md
src/RNCWebViewNativeComponent.ts
src/WebViewTypes.ts

Allowing the prop `refreshControlLightMode`, which allows us to change the color of the refreshControl tintColor to white.
It's off by default, and will allow the color to remain the default color (a dark gray on iOS at the moment).
Screen recording attached when the property is set to true.
Sort of solves https://github.com/react-native-webview/react-native-webview/issues/3478, by allowing light mode. We could go further by giving it a specific color, but I think this solves my use case.
https://github.com/react-native-webview/react-native-webview/assets/170964316/9576f9c6-d945-4d38-8aec-22301e22d5ed

feat (iOS):Allow light mode refresh control ios

---

package.json

This is the last version of escape-string-regexp before it's rewritten to ES modules.
Updating past 3.x requires at least node 10, but that is already a very old node version.
https://github.com/sindresorhus/escape-string-regexp/releases

Update escape-string-regexp to 4.x

---

android/src/newarch/com/reactnativecommunity/webview/RNCWebViewManager.java

fix `Class 'RNCWebViewManager' must either be declared abstract or implement abstract method 'setRefreshControlLightMode(T, boolean)' in 'RNCWebViewManagerInterface'` and `Class 'RNCWebViewManager' must either be declared abstract or implement abstract method 'setAllowsPictureInPictureMediaPlayback(T, boolean)' in 'RNCWebViewManagerInterface'` errors.
```
> Task :react-native-webview:compileDebugJavaWithJavac FAILED
projectX/react-native-webview/android/src/newarch/com/reactnativecommunity/webview/RNCWebViewManager.java:36: error: RNCWebViewManager is not abstract and does not override abstract method setRefreshControlLightMode(RNCWebViewWrapper,boolean) in RNCWebViewManagerInterface
public class RNCWebViewManager extends ViewGroupManager<RNCWebViewWrapper>
^
Note: …
```

fix: Implement missing methods of RNCWebViewManagerInterface

---

apple/RNCWebViewImpl.m
yarn.lock

On iOS/macOS, the previous code had an issue where HTTP error handling and file download logic in the `webView:decidePolicyForNavigationResponse:decisionHandler:` method was only being executed for main frame responses (due to the navigationResponse.forMainFrame check). This meant that responses from iframes were not being properly handled, potentially leading to security issues or missed file downloads.
This PR (credit to @ugwst-sec for the tip) fixes that issue by changing the conditional logic.
(Tip: turn off "whitespace" in the diff -- it's a pretty minimal change, but the indentation change makes the diff look scarier than it is.)

fix(apple): Updates how HTTP errors are handled

---

android/src/newarch/com/reactnativecommunity/webview/RNCWebViewManager.java

No need to manually call the methods, the generated delegate already does that for us.
Fixes #3305

fix(android, new arch): Do not execute commands twice

---

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManagerImpl.kt
android/src/newarch/com/reactnativecommunity/webview/RNCWebViewManager.java
android/src/oldarch/com/reactnativecommunity/webview/RNCWebViewManager.java

on android and react-native new architecture mode, even with `allowFileAccess`, the initial loading to `file:///` will fail with `net:ERR_ACCESS_DENIED` error.
on new architecture mode updating `source` will go first before `allowFileAccess` in the `RNStylesDiffMap`. we cannot always ensure the order of updating props. on ios implementation, the webview will delay its call to `loadRequest:`. this pr tries to add a similar mechanism on android. we will try to load URL after all updates are finalized.
- i have a repro at https://github.com/Kudo/repro-webview-late-props
- test react-native-webview's example to check for any regressions

fix(android): allowFileAccess does not apply to initial loading

---

apple/RNCWebViewImpl.m

PR #3559 which was committed by e8f3c0e causes a regression in a patch release (v13.12.3).
Issue #3578 is open for more than a month and there's even another patch release released after that (v13.12.4).
I'm worried that this regression would be buried and stay unnoticed if we continue ignoring it and don't address.
For more context, Expo DOM (use dom) just started to gain some traction and it relies on RNWV.
Expo managed version of RNWV is 13.12.4 and it'd definitely hit much more people very soon when people start to use it more often.
Maybe pre-13.12.3, this regression wasn't a wild-spread issue but I think we're about to see a lot more people facing it.
Let's revert this relatively small and easy to undo PR and try again another day in another attempt to fix the original issue?

revert (e8f3c0e) fix(iOS): preload WebView on initial render in background tabs

---

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManagerImpl.kt

this is needed because of [this change in the core](https://github.com/facebook/react-native/commit/145c72f8163048f0eee30d5ce850911f5dad865c#diff-cab6c32d3e05344091c804ea93e8a220dabdd75ec2a258aaf4bde7751c13f844R31)
this should be backward compatible

feat: support RN 0.77

---

apple/RNCWebView.mm

All canGoForward values on iOS are using canGoBack. This PR fixes that.
Fixes #3614

fix(ios): use correct property for canGoForward value for return values

---

docs/Guide.md

I was trying out this section of the guide and was surprised to find it didn't work. After adding some log statements, I observed that the issue is that while the `useCallback` correctly sets `canGoBack` as a dependency, the `useEffect` wasn't depending on the `onAndroidBackPress` value which changes whenever `canGoBack` changes, thus the registered event listener always had the initial `false` value for `canGoBack`.

Fix missing hook dependency in Android back press example

---

apple/RNCWebViewImpl.h
apple/RNCWebViewImpl.m

At my side of Microsoft, we have recently "vendored" a couple of libraries. Which means, we started building them from source using our own generated Xcode project (not the one cocoapods generates), which has much stricter build flags / treats warnings as errors. In doing so, I caught a couple of issues in React Native Webview I'd like to push back up!
Namely:
- `RNCWebViewImpl` should implement the protocol `UIGestureRecognizerDelegate`. It already was, but it wasn't listed so at the header.
- Without this,I got the error `Assigning to 'id<UIGestureRecognizerDelegate> _Nullable' from incompatible type 'RNCWebViewImpl *const __strong' ` on line 565 when we try to set `self` as a `UILongPressGestureRecognizer` delegate. 
- Move some macOS ifdefs around so that RNWWebViewImpl conforms to …

chore(apple): fix some Xcode warnings caught internally

---

android/src/main/java/com/reactnativecommunity/webview/RNCWebView.java

fix a regression from #3609, not sure if it is the android 9 issue.
on the fallback onMessage path, the `mWebView.getUrl()` will throw exception because it's not on main thread.
post onMessage execution on main thread

fix(android): onMessage exception on fallback path

---

android/src/newarch/com/reactnativecommunity/webview/RNCWebViewManager.java

When running the StaticViewConfig validator on Bridgeless, it fails with this error:
```js
import * as NativeComponentRegistry from 'react-native/Libraries/NativeComponent/NativeComponentRegistry';
...
if (global.RN$Bridgeless === true && __DEV__) {
NativeComponentRegistry.setRuntimeConfigProvider(name => ({
native: false,
verify: true,
}));
}
```
```log
console.js:655 Warning: StaticViewConfigValidator: Invalid static view config for 'RNCWebView'.
- 'validAttributes.suppressMenuItems ' is missing.
```
The spec has the prop:
https://github.com/react-native-webview/react-native-webview/blob/87b2265d6e5e700ca607ddd64e75997c9e6ca35a/src/RNCWebViewNativeComponent.ts#L245
The issue is due to an extra space in the Prop Name for `suppressMenuItems` in the Android Native View Config.
Thus causing …

[fix][android] Fix suppressMenuItems native view config name with extra space causing StaticViewConfigValidator to fail

---

android/src/main/java/com/reactnativecommunity/webview/RNCWebView.java
android/src/main/java/com/reactnativecommunity/webview/RNCWebViewClient.java
android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManagerImpl.kt

Hey folks, in https://github.com/react-native-webview/react-native-webview/pull/1221, this code was added as a workaround for some Chromium bugs: https://issues.chromium.org/issues/40658278 and https://issues.chromium.org/issues/40673276.
https://issues.chromium.org/issues/40658278 was marked a duplicate of https://issues.chromium.org/issues/40671896, which is marked as fixed. https://issues.chromium.org/issues/40673276 is also marked as fixed.
I think we're good to revert this, and I am currently working on a project that would like to have this revert sorted out so we can rely on `onReceivedError` to pass all the messages it gets.

fix: revert 1221 setIgnoreErrFailedForThisURL

---

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewClient.java
android/src/main/java/com/reactnativecommunity/webview/events/SubResourceErrorEvent.kt
android/src/newarch/com/reactnativecommunity/webview/RNCWebViewManager.java
android/src/oldarch/com/reactnativecommunity/webview/RNCWebViewManager.java
example/App.tsx
example/examples/SslError.tsx
src/RNCWebViewNativeComponent.ts
src/WebView.android.tsx
src/WebViewShared.tsx
src/WebViewTypes.ts

This PR adds a new event handler to the `WebView` component for Android: `onLoadSubResourceError`, which is fired when the package receives SSL errors where the failing URL does not match the top window URL.
Currently, `react-native-webview` simply logs these out. But I had a use case where I needed to specifically handle these events. This patch works for my use case, and it seems reasonable other people might want something like this as well.
A simpler change might be to change `TopLoadingErrorEvent` to have some value indicating that `failingUrl !== topWindowUrl`, and just route everything through the existing handler. As a starting proposal, I chose to add a separate handler for this because I figured it was more backwards compatible. Happy to iterate on that if the project prefers a …

Add sub resource SSL error handling on Android

---

index.d.ts

Since `clearCache` is available on Android, Apple and Windows platforms, we should remove the optional modifier for `clearCache`

fix(types): Make `clearCache` method required instead of optional
