README.md
=> Add @Titozzz to maintainers

android/build.gradle
Try to use Android tooling config from React Native
=> try reuse Android tooling config from React Native

docs/Reference.md
I think `injectJavaScript` is a method, not a props.
=> Modified the document for `injectJavaScript`

package.json, typings/index.d.ts, yarn.lock
Typescript definitions are based on flow
Tested them a bit in my project
I think couple of event types are screwed in flow definitions (synthetic/non-synthetic are mixed), tried my best to test which events are really received.
=> Add typescript definitions

ios/RNCWKWebView.m
There is a problem that the `mediaPlaybackRequiresUserAction` option does not work under iOS 10.
I hope this helps.
=> Fixed for supporting mediaPlaybackRequiresUserAction option under iOS 10.

docs/Reference.md, ios/RNCWKWebView.h, ios/RNCWKWebView.m, ios/RNCWKWebViewManager.m, js/WebView.ios.js, js/WebViewTypes.js, typings/index.d.ts
Resolve this [issue](https://github.com/react-native-community/react-native-webview/issues/153)
=> [ios] Add 'pagingEnabled' property to the iOS WKWebview

typings/index.d.ts
I considered moving everything over to typescript but I got hung up on importing android.js vs ios.js. Pretty annoying to deal with...
=> More better types

typings/index.d.ts
so happy to see there is typing in the newest release.
I added back WebViewIOSLoadRequestEvent which also exist in react-native typing and fix startInLoadingState which should be boolean.
=> Fixing typing.

ios/RNCWKWebView.m
=> Fix JavaScript alert not working in IOS

ios/RNCWKWebView.m
Reverts https://github.com/react-native-community/react-native-webview/pull/134 to fix https://github.com/react-native-community/react-native-webview/issues/201
=> Fixes issue where keyboard dismiss would scroll to top

README.md
Adds a testimonial from Garrett McCollough (with his permission) to the README.
=> chore(docs): Add testimonial to README

android/build.gradle
fixes #174 
fixes #184 
fixes #245
=> fix(gradle): Add support library as a dependency

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java
Fixed issue #266. Now downloading works on Motorola Moto One with Android 9.
=> Fix for issue #266

README.md
Just a minor correction of the anchor link in Readme file.
=> Updated emoji key link in Readme.md 🧐

docs/Custom-Android.md
Doc is now up-to-date with latest `react-native-webview` changes
=> Reflect migration to react-native-webview project

docs/Reference.md
Per #320, this adds an example for onShouldStartLoadWithRequest.
=> Adds example for onShouldStartLoadWithRequest

ios/RNCWKWebView.m
=> fix(WKWebView Scrolling): fixed broken scroll

package.json, yarn.lock
You might've noticed that recent pull requests have failed tests due to wrong versions in package.json
=> fix flow error

package.json, yarn.lock
https://nvd.nist.gov/vuln/detail/CVE-2018-16469
=> fix(vulnerability): merge issue

docs/Reference.md, ios/RNCUIWebViewManager.m, ios/RNCWKWebView.h, ios/RNCWKWebView.m, ios/RNCWKWebViewManager.m, js/WebView.ios.js, js/WebViewTypes.js, typings/index.d.ts
Same as ScrollView's `directionalLockEnable`.
=> feat: add prop `directionalLockEnabled` for iOS

android/.editorconfig, android/src/main/AndroidManifest.xml, android/src/main/java/com/reactnativecommunity/webview/RNCWebViewFileProvider.java, android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java, android/src/main/java/com/reactnativecommunity/webview/RNCWebViewModule.java, android/src/main/java/com/reactnativecommunity/webview/RNCWebViewPackage.java, android/src/main/java/com/reactnativecommunity/webview/events/TopLoadingErrorEvent.kt, android/src/main/java/com/reactnativecommunity/webview/events/TopLoadingFinishEvent.kt, android/src/main/java/com/reactnativecommunity/webview/events/TopLoadingProgressEvent.kt, android/src/main/java/com/reactnativecommunity/webview/events/TopLoadingStartEvent.kt, android/src/main/java/com/reactnativecommunity/webview/events/TopMessageEvent.kt, android/src/main/java/com/reactnativecommunity/webview/events/TopShouldStartLoadWithRequestEvent.kt, android/src/main/res/xml/file_provider_paths.xml
Added an extremely simple `.editorconfig` I inferred from the main part of the project, then reformatted the codebase according to it. 🙂
=> chore(format): Android project formatting

ios/RNCWKWebView.m
This fixes #62 for iOS 12. It listens for a specific notification that is only fired when entering / exiting fullscreen. I tested on simulator and device with iOS 12.2. This PR also attempts to preserve the state of the status bars when the web view was initialized.
=> fix(WKWebView): StatusBar is gone after fullscreen (iOS 12)

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java
=> Fix geolocation access

docs/Getting-Started.md
=> npm install instructions to docs

ios/RNCWKWebView.m
Resolve
https://github.com/react-native-community/react-native-webview/issues/559
https://github.com/react-native-community/react-native-webview/issues/513
=> fix(iOS WKWebView): contentInset not properly applied

docs/Reference.md
This is a minor documentation update.
Added a note about the baseUrl usage since this has been the cause of some filed issues e.g. https://github.com/react-native-community/react-native-webview/issues/526#issuecomment-498067637
There were no code changes
=> chore(docs): Added additional note to `source` parameter

README.md
=> Fix npmjs hyperlink in readme

react-native-webview.podspec
=> fix quotes

react-native-webview.podspec
Fixes #680
Follow reproduce steps from issue
| Android |    Not applicable     |
None of these is applicable, it's installation bugfix
=> Podspec source format fix

src/WebView.tsx
Minor comment phrasing suggestion
=> Comment phrasing suggestion

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java, android/src/main/java/com/reactnativecommunity/webview/events/TopMessageEvent.kt
Fixes #119 
Opening this as #120 seems to be stuck on merge conflicts.
Used the code snippet provided by @keenubee on the thread at #129 
Have tested this and confirmed its working on device and simulator.
=> Fix onMessage on android to also include navigation state properties

docs/Custom-Android.md
"Native UI Components" needs to link to the main React Native site, not within this repo.
Minor documentation fix to broken link in Custom-Android.md
=> chore(docs): Fixed broken link in Custom-Android.md

.github/workflows/detox.yml
This is an initial attempt at adding a Github Action to run CI / Detox tests.
=> chore(Github Actions): Added detox.yml workflow Github Action

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java
=> fix(Android): hardware acceleration issue

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java
=> fix(android scroll): revert #281 that caused new issues

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java, docs/Reference.md, src/WebViewTypes.ts
This solves #888.
Exposes `cacheMode` to javascript component.
For testing, I linked my fork and updated my app with it. Worked as expected.
Create a `WebView` component and pass the `cacheMode` attribute.
=> feat(android): Expose cacheMode property

src/WebViewTypes.ts
Fixes the following TypeScript typing issue:
```
Interface 'RNCWebViewUIManager' incorrectly extends interface 'UIManagerStatic'.
Types of property 'getViewManagerConfig' are incompatible.
Type '(name: string) => { Commands: WebViewCommands; }' is not assignable to type '(name: string) => { Commands: { [key: string]: number; }; }'.
Type '{ Commands: WebViewCommands; }' is not assignable to type '{ Commands: { [key: string]: number; }; }'.
Types of property 'Commands' are incompatible.
Type 'WebViewCommands' is not assignable to type '{ [key: string]: number; }'.
Index signature is missing in type 'WebViewCommands'.
export interface RNCWebViewUIManager extends UIManagerStatic {
```
* Fixes #901 
* Update WebViewCommands type so that it can be used as an index signature
| OS      | …
=> fix(deps): Fix RNCWebViewUIManager interface typescript error (#901)

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java
=> Fixing possible NullPointerException in setHardwareAccelerationDisabled

docs/Guide.md
=> Added missing word to Deep Guide

docs/README.portuguese.md
I was using this solution a lot, so I decided to translate it into my language.
=> chore(docs): README.md translated into Brazilian portugues

.github/workflows/detox.yml
I enabled `--frozen-lockfile` yarn's flag
https://yarnpkg.com/lang/en/docs/cli/install/#toc-yarn-install-frozen-lockfile
`yarn install` without this flag may update packages during installation. The flag is required for reproducible dependencies which is usually common on CI 
=> enable --frozen-lockfile yarn flag

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewModule.java
Only deleting obsolete comments, not needed anymore because the code was changed.
=> chore(cleaning): Remove old comments

docs/Reference.md, ios/RNCWebView.h, ios/RNCWebView.m, ios/RNCWebViewManager.m
Fixes https://github.com/react-native-community/react-native-webview/issues/970
=> Make allowFileAccessFromFileURLs work in iOS.

ios/RNCWebView.m
=> Ignore WebKitDomainError 101

README.md
=> chore(docs): Add 8.0.0 to Breaking History on README

README.md
This PR is part of https://github.com/react-native-community/.github/issues/45
Added LeanCore extracted badge in README. 
Also adjusted the style of npm badge to match the other badges.
I tried to have the github badge match the other badge's style as well, but [github badges](https://github.com/ddavison/github-badges) did not seem to have an option for flat-square style.
=> Add LeanCore badge to readme

docs/README.portuguese.md
=> Fix Getting Started Guide link in Breaking History

README.md, bin/setup, docs/Custom-Android.md, docs/Getting-Started.md, docs/Guide.md, docs/README.portuguese.md, docs/Reference.md, example/android/app/build.gradle
This PR update react native docs links to new domain: reactnative.dev
Open links in changed files
=> docs: update documentation links to reactnative.dev

package.json
Adding a `^`.
0. [System requirments](https://microsoft.github.io/react-native-windows/docs/rnw-dependencies).
1. Run `yarn start:windows`.
2. Open `example/windows/WebViewWindows.sln` with VisualStudio and run.
| Windows | ✅ |
=> Fix react-native-windows dependency version

package.json
`rnpm-plugin-windows` has recently been added to dependencies, adding quite large number of transitive dependencies for users of `react-native-webview`. Looking at the documentation of `rnpm-plugin-windows` it seems to be used for project creation. Does it do anything for end users? This PR moves it to devDependencies. If I missed that it's needed for something, feel free to close this PR.
Tsc and tests pass.
=> Move rnpm-plugin-windows to devDependencies

package.json, src/WebView.android.tsx, src/WebViewShared.tsx
It seems to be an issue in latest releases affecting Android.
Here I use ~the [solution described by @DomiR](https://github.com/react-native-community/react-native-webview/issues/1312#issuecomment-613359818)~ the solution described in conversation.
Closes #1312
I guess that `./yarn.lock` should be also regenerated, but let's leave it as it is and do it if the PR is accepted. 
I used to test it in the project I currently working on.
```
"react-native": "0.62.2",
"react-native-webview": "^9.2.1"
```
Pixel 3, Android 10
```
➜ npx envinfo --preset react-native
System:
OS: macOS 10.15.3
CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
Binaries:
Node: 13.2.0 - ~/.nvm/versions/node/v13.2.0/bin/node
Yarn: 1.19.2 - ~/.nvm/versions/node/v13.2.0/bin/yarn
npm: 6.13.7 - …
```
=> fix(Android): uuid generation issue

.circleci/config.yml, .github/workflows/detox.yml, .github/workflows/scripts/install-vs-features.ps1, .github/workflows/windows-ci.yml, .gitignore, __tests__/Alert.test.js, example/windows/.gitignore, example/windows/WebViewWindows/Package.appxmanifest, example/windows/WebViewWindows/WebViewWindows.vcxproj, example/windows/WebViewWindows/WebViewWindows.vcxproj.filters, jest-setups/jest.setup.js, jest-setups/jest.setup.windows.js, package.json, yarn.lock
Setup Windows CI checks using GitHub action and added one simple UI test.
=> Set up Windows CI

android/build.gradle
=> fix(android): Broken build due to conditional import of kotlin

docs/Custom-Android.md
The docs contained an old link that 404s, linking to the old repo, this just updates that link so it works.
N/A
N/A
Go [here](https://github.com/react-native-community/react-native-webview/blob/master/docs/Custom-Android.md) and click ' native code for web views', you will get a 404.
=> Documentation: Update link in custom-android docs

.github/workflows/windows-ci.yml, metro.config.windows.js
Cleaning up Windows CI, removed some unnecessary steps.
=> Cleanup windows ci

docs/Guide.md
**Updated Guide.md for using injectedJavaScript**
Based on the issue https://github.com/react-native-community/react-native-webview/issues/1554.
=> chore(docs): Updated Guide.md for using injectedJavaScript

apple/RNCWebView.m
The current code to obtain the top view controller is outdated for about 2 years already.  The current recursive approach has a few bugs, such as not working within modals, or needing extra checks for file pickers.
This update makes use of `RCTPresentedViewController` used throughout various other RN libraries, and implemented by RN itself, making the code much more readable and fixing the above issues.
This should close https://github.com/react-native-community/react-native-webview/issues/1585 without also breaking the changes implemented in https://github.com/react-native-community/react-native-webview/issues/1325
Tested on iPhone 7 (13.6).  Tested webviews within a regular screen and a Modal, and also tested the use case with a file picker and an alert shown right aftewards. No crashes …
=> Fix the way the top view controller is obtained.

package.json
WebView is locking the version from the latest React Native version. https://github.com/react-native-community/react-native-webview/issues/1581 & https://github.com/react-native-community/react-native-webview/issues/1445, we should not have an upper version lock so developers can report issues with the latest RN version
- [] I added the documentation in `README.md`
=> fix(deps): Update package.json

index.d.ts
Add missing `postMessage`, `clearFormData`, `clearCache` and `clearHistory` methods to the type definition file.
No code change, only Typescript definitions.
=> fix(types): Update Typescript definition file

README.md
The link to v2.0.0 tag looks broken so I fixed it.
=> Fix link to v2.0.0

.all-contributorsrc, README.md, apple/RNCWebView.m, docs/Custom-Android.md, docs/Guide.md, docs/README.portuguese.md, package.json, react-native-webview.podspec
This PR updates the references to this repo, needed after the transfer (see [here](https://twitter.com/jamonholmgren/status/1309624716726951936)).
```diff
-/react-native-community/react-native-webview
+/react-native-webview/react-native-webview
```
=> refactor: update repo references with new repo location

package.json, yarn.lock
This should fix the failing Windows CI.
=> Upgrade react-native-windows to 0.63.11

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java
Using a WebView within a Modal component causes a bunch of issues when trying to play video in full screen mode in Android when using `allowsFullscreenVideo={true}`.
This PR improves the View hierarchy handling to check for a Modal or differences in the root view in order to correctly decide which View to hide when playing video in full screen.
The change should be fully compatible with current usages.
Should fix: https://github.com/react-native-webview/react-native-webview/issues/1293
=> Fix Android full screen video when in modals

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java
Missing permissions for DRM protected content
https://github.com/react-native-webview/react-native-webview/issues/1849
=> DRM protection

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java
Create Issue#https://github.com/react-native-webview/react-native-webview/issues/1938
=> Converting dispatchEvent static method to non static method

android/build.gradle, android/gradle.properties
=> fix(android): read minSdkVersion from root project

docs/Debugging.md
This documentation-only update provides some more useful JS debugging tips
=> chore(docs): Adds some simple webview JS debugging tips

README.md
Add Alex and Chiara to Readme as maintainers.
=> Add Alex and Chiara as Maintainers

android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java
=> fix(android): onPermissionRequest duplicate #1239 #2001

windows/ReactNativeWebView/ReactWebViewManager.cpp
Fixes issue https://github.com/react-native-webview/react-native-webview/issues/2097
=> fix(windows): Navigation to ms-appdata and ms-appx-web local file request on Windows

docs/README.portuguese.md
Hi guys, how are you?
In this PR:
- I have updated the content pt-br of README.
=> Update content in readme pt-br

docs/Reference.md
- Fix missing curly braces in onCustomMenuSelecton example
- Fix the missing ``` code closing (markdown) in forceDarkOn example
=> Fix missing curly braces and ``` Reference.md

apple/RNCWebView.h, apple/RNCWebView.m, apple/RNCWebViewManager.m, docs/Reference.md, package.json, src/WebView.ios.tsx, src/WebViewTypes.ts
Added prop `textInteractionEnabled`. Only supported on iOS 15+
When set to `false` disables all text interaction.
=> Added textInteractionEnabled prop

README.md, docs/README.french.md, docs/README.portuguese.md
I forgot the update the other READMEs to make the french version visible
=> Update of the links to the READMEs

docs/Contributing.md, docs/Contributing.portuguese.md, docs/Custom-Android.portuguese.md, docs/Custom-iOS.md, docs/Custom-iOS.portuguese.md, docs/Debugging.md, docs/Debugging.portuguese.md, docs/Getting-Started.md, docs/Getting-Started.portuguese.md, docs/Guide.md, docs/Guide.portuguese.md, docs/Reference.md, docs/Reference.portuguese.md
Translation of all documentation to Brazilian Portuguese.
=> doc: portuguese documentation translation

apple/RNCWebView.m
Implements improvements to the cookie sharing feature.
* Sync the cookies from `NSHTTPCookieStorage` to the WebView before visiting the source. Previously due to concurrency issues it was possible that the source would requested *before* the cookies had been written to the WebView's data store.
* Sync the cookies back *from* the WebView to `NSHTTPCookieStorage` after navigation completes
=> feat(iOS): Cookie sharing improvements

docs/Getting-Started.md
Update Getting Started information to match current support for WebView2.
=> fix(windows): Update Getting Started information for Windows

docs/Reference.portuguese.md
After updating the English version of Reference.md, the portuguese one was not updated.
=> Update Portuguese reference (add clearCache ex)

docs/Guide.md
This closes #2466.
Here's a commit where this was successfully implemented: https://github.com/peterklingelhofer/stream-app/commit/645547530367a60b73c09aa621b66ee22478eafa.
=> chore(docs): add page navigation gesture & button support

package.json, yarn.lock
Although my local build has been passing, the Android CI is failing with errors that look related to https://github.com/facebook/react-native/issues/35210
=> Update React Native to fix Android build

docs/Reference.md, docs/Reference.portuguese.md
The id for the clearCache method is clearCachebool, but the index was incorrectly only referencing clearCache.
=> Fix clearCache link in index

README.md
Pretty tiny updates to the README.
=> README fixes: badge, minor wording tweaks

src/WebView.android.tsx, src/WebView.ios.tsx, src/WebView.macos.tsx, src/WebView.windows.tsx, src/WebViewShared.tsx
already known but I just want to fix this 😊 (https://github.com/react-native-webview/react-native-webview/pull/2508#discussion_r894953827)
=> Fix `useWebViewLogic` typo

README.md, docs/Contributing.italian.md, docs/Contributing.md, docs/Contributing.portuguese.md, docs/Custom-Android.italian.md, docs/Custom-Android.portuguese.md, docs/Custom-iOS.italian.md, docs/Custom-iOS.md, docs/Custom-iOS.portuguese.md, docs/Debugging.italian.md, docs/Debugging.md, docs/Debugging.portuguese.md, docs/Getting-Started.italian.md, docs/Getting-Started.md, docs/Getting-Started.portuguese.md, docs/Guide.italian.md, docs/Guide.md, docs/Guide.portuguese.md, docs/README.french.md, docs/README.italian.md, docs/README.portuguese.md, docs/Reference.italian.md, docs/Reference.md, docs/Reference.portuguese.md
Hi there 👋🏼
I've been using this package since its early days and thought it was time for me to help pay back all hours it saved me.
I took the liberty of translating these docs in Italian and while I was at it, fixed up some minor inconsistencies and typos here and there (hopefully that's okay).
If anything needs changing, just let me know!
=> docs(lang): Add Italian translation to the docs 🇮🇹📖

android/build.gradle, android/src/main/AndroidManifestNew.xml
RN Team Update:
https://github.com/react-native-community/discussions-and-proposals/issues/671
Fix:
https://github.com/react-native-community/discussions-and-proposals/issues/671#issuecomment-1598892444
=> Android RN 72 Support - Update build.gradle w/ Namespace

README.md
Grammar issues in README.md were resolved to improve comprehensibility.
=> Fixed grammar issues in README.md

windows/ReactNativeWebView/packages.config
Fixes https://github.com/react-native-webview/react-native-webview/issues/3189 and https://github.com/react-native-webview/react-native-webview/issues/1861
=> Fix NuGet package reference

src/WebViewTypes.ts
=> fix: Indentation error

package.json
=> fix: broken typings after moving to babel build from tsc

src/WebView.macos.tsx
**Context**
- RN MacOS can be built w/ the new Arch
- `cd example/macos && RCT_NEW_ARCH_ENABLED=1 pod install`
- RN Webview was not working on MacOS since we were not passing the correct `newSource={newSource}` prop that the Fabric component requires.
https://github.com/react-native-webview/react-native-webview/blob/7420ed8e02291a7749d34c6f2c95b1a077319545/src/RNCWebViewNativeComponent.ts#L279
- implementation copied from ios: 
https://github.com/react-native-webview/react-native-webview/blob/7420ed8e02291a7749d34c6f2c95b1a077319545/src/WebView.ios.tsx#L267
**Change**
- Use iOS new arch api for macOS
**Fabric**
https://github.com/react-native-webview/react-native-webview/assets/96719/869e39db-4f26-45d0-a963-4287f1cca156
**Paper**
=> [fix][macos][fabric] Add correct source prop for macOS new arch support

docs/Guide.md
Adds documentation for how to fix an issue with the capture attribute on file inputs described in #3288.
Thanks @bbergler for the solution!
=> Add documentation for the capture attribute on file inputs

apple/RNCWebViewImpl.m
Hi there!
Sorry for the lack of details in this PR. I'm not great with English, and this is my first time with Objective-C. This change is related to issues we've been discussing.
Feel free to ask questions or suggest changes. I'm open to any feedback and eager to learn.
---
PRs:
- https://github.com/react-native-webview/react-native-webview/pull/2930
- https://github.com/react-native-webview/react-native-webview/pull/3041
Issues:
- https://github.com/react-native-webview/react-native-webview/issues/2431
- https://github.com/react-native-webview/react-native-webview/issues/3481
=> fix(ios): Fix webview not loading in background

android/src/main/java/com/reactnativecommunity/webview/RNCWebView.java, apple/RNCWebViewImpl.m
https://github.com/react-native-webview/react-native-webview/issues/3439
=> fix(android,ios): Sending correct url in onMessage callback

apple/RNCWebViewImpl.m
=> fix(ios, new-arch): Fixed regression caused by new defaults applied

index.d.ts
The clearCache method is availalbe on both android and iOS. The comment is very outdated.
=> Update JSDOC for clearCache
